// ─── Luminae Card Lore ──────────────────────────────────────────────────────
// Names + flavor text sourced from LUMINAe_ARTIFACT_REPLACEMENT_TABLE_v0.3_SCALE_AS_CAPABILITY.md
// Metadata fields (artifactForm, blueprintRole, blueprintFamilies, civLane,
// engineeringScale, artPrompt) also sourced from v0.3 — all optional so
// existing consumers that only read name/flavor are unaffected.
// Do NOT edit names, flavor, or metadata manually — update via the replacement table.

export interface CardLore {
  name: string;
  flavor: string;
  artifactForm?: string;
  blueprintRole?: string;
  blueprintFamilies?: string;
  civLane?: string;
  engineeringScale?: "Planetary" | "Star-system" | "Galactic";
  artPrompt?: string;
}

const CARD_LORE: Record<string, CardLore> = {
  // ── Tier 1 ─ Flare ───────────────────────────────────────────────────────
  t1r01: { name: "Ignition Kernel",       flavor: "A dense ignition core that can start a city, a shipyard, or a rescue furnace without becoming a weapon first.",
    artifactForm: "Power Component / Control Instrument", blueprintRole: "controlled ignition and thermal regulation",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Planetary Cradle Engine", civLane: "planetary forge culture",
    engineeringScale: "Planetary", artPrompt: "Red-orange contained plasma in dark metal channels." },
  t1r02: { name: "Ashroot Bloom",         flavor: "A fire-adapted root organ that turns disaster ash into the first useful tissue of recovery.",
    artifactForm: "Biotech Module / Catalyst", blueprintRole: "post-burn ecological recovery",
    blueprintFamilies: "Planetary Cradle Engine; Stellar Nursery Rite precursor", civLane: "phoenix biosphere",
    engineeringScale: "Planetary", artPrompt: "Charred roots with contained ember veins and new growth." },
  t1r03: { name: "Chrono-Ember Core",     flavor: "A warm memory-core that records when a fire should return, not merely how hot it burned.",
    artifactForm: "Archive / Power Component", blueprintRole: "energy-memory synchronization",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Spiral-Arm Archive precursor", civLane: "deep-time ignition culture",
    engineeringScale: "Planetary", artPrompt: "Small ember core with time rings, not a giant clock or star." },
  t1r04: { name: "Causal Spark Coil",     flavor: "A trigger coil that refuses to fire unless the next three consequences remain survivable.",
    artifactForm: "Control Instrument / Protocol Object", blueprintRole: "safe trigger sequencing",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Causality Audit Court precursor", civLane: "experimental causal engineer civilization",
    engineeringScale: "Planetary", artPrompt: "Compact coil with spark arcs suspended in precision housing." },
  t1r05: { name: "Voidflare Cask",        flavor: "A sealed cask that converts hidden pressure into one brief flare a city can survive.",
    artifactForm: "Containment / Power Component", blueprintRole: "volatile void-pressure ignition",
    blueprintFamilies: "Worldshield Covenant; Mantle-to-Orbit Foundry", civLane: "eclipse host civilization",
    engineeringScale: "Planetary", artPrompt: "Dark cask with red-violet pressure glow, small artifact focus." },
  t1r06: { name: "Photosynthetic Wick",   flavor: "A living wick that feeds on sunlight and releases heat slowly enough for a cold settlement to endure.",
    artifactForm: "Biotech Module / Power Component", blueprintRole: "biological energy conversion",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "solar-adapted biosphere civilization",
    engineeringScale: "Planetary", artPrompt: "Plantlike wick with amber energy capillaries, no giant sun array." },
  t1r07: { name: "Entropy Pyre Baffle",   flavor: "A heat baffle that teaches waste where to go before it teaches the city how to die.",
    artifactForm: "Containment / Thermal Control", blueprintRole: "waste heat and decay routing",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Worldshield Covenant", civLane: "entropy-tolerant industrial culture",
    engineeringScale: "Planetary", artPrompt: "Heat sink baffle with soot, glowing vents, precise containment fins." },
  t1r08: { name: "Oathfire Igniter",      flavor: "An igniter that only opens in the presence of witnesses, making fire a civic act instead of a private threat.",
    artifactForm: "Civic Signal Object / Power Component", blueprintRole: "public sanctioned ignition",
    blueprintFamilies: "Worldshield Covenant; Ecumenopolis Lattice", civLane: "solar civic forge culture",
    engineeringScale: "Planetary", artPrompt: "Ceremonial but functional ignition tool with gold-red glow, no text." },

  // ── Tier 1 ─ Continuum ───────────────────────────────────────────────────
  t1s01: { name: "Echo Splinter",         flavor: "A broken sliver of recorded cause, useful because it remembers the sound before the disaster.",
    artifactForm: "Archive / Sensor", blueprintRole: "event echo capture",
    blueprintFamilies: "Spiral-Arm Archive precursor; Worldshield Covenant", civLane: "planetary memory culture",
    engineeringScale: "Planetary", artPrompt: "Blue crystal splinter with faint echo rings." },
  t1s02: { name: "Causal Ember Relay",    flavor: "A relay that passes heat, signal, and consequence in the same controlled pulse.",
    artifactForm: "Interface / Protocol", blueprintRole: "local cause-effect relay",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Causality Audit Court precursor", civLane: "predictive engineering culture",
    engineeringScale: "Planetary", artPrompt: "Small relay node with amber-blue causal traces." },
  t1s03: { name: "Null-Loop Anchor",      flavor: "An anchor that ends a loop before a city mistakes repetition for immortality.",
    artifactForm: "Control Instrument / Stabilization", blueprintRole: "recursion boundary control",
    blueprintFamilies: "Worldshield Covenant; Causality Audit Court precursor", civLane: "recursion-safety civilization",
    engineeringScale: "Planetary", artPrompt: "Compact anchor ring with blue-black recursive markings, no text." },
  t1s04: { name: "Time-Crystal Scaffold", flavor: "A scaffold grown from timing crystals, used wherever machines must agree on the same second.",
    artifactForm: "Material / Fabrication Tool", blueprintRole: "precision timing substrate",
    blueprintFamilies: "Ecumenopolis Lattice; Matrioshka Mind precursor", civLane: "timekeeping material culture",
    engineeringScale: "Planetary", artPrompt: "Crystalline scaffold component, not a full building." },
  t1s05: { name: "Silent Recursion Rule", flavor: "A recursion rule copied in silence because speaking it aloud changes the system it protects.",
    artifactForm: "Protocol / Archive", blueprintRole: "quiet error correction",
    blueprintFamilies: "Matrioshka Mind precursor; Worldshield Covenant", civLane: "quiet planner civilization",
    engineeringScale: "Planetary", artPrompt: "Abstract protocol token or etched wafer, no readable text." },
  t1s06: { name: "Living Chronicle",      flavor: "A chronicle that grows new margins when the people it records learn to become someone else.",
    artifactForm: "Archive / Biotech Module", blueprintRole: "adaptive civic memory",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "biological archive civilization",
    engineeringScale: "Planetary", artPrompt: "Organic book-like memory organ with blue-green veins, no letters." },
  t1s07: { name: "String-Scar Loom",      flavor: "A loom that turns flaws in exotic threads into repeatable manufacturing instructions.",
    artifactForm: "Fabrication Tool / Material", blueprintRole: "defect-pattern weaving",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Galactic Relic Forge precursor", civLane: "defect-engineer culture",
    engineeringScale: "Planetary", artPrompt: "Small precision loom with luminous tension threads." },
  t1s08: { name: "Root Memory Valve",     flavor: "A valve grown into old roots, opening only enough ancestral memory for the present to survive.",
    artifactForm: "Archive / Biotech Module / Control Instrument", blueprintRole: "selective memory release",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "ancestral biosphere civilization",
    engineeringScale: "Planetary", artPrompt: "Rooted valve with blue-green memory glow, no giant forest." },

  // ── Tier 1 ─ Verdance ────────────────────────────────────────────────────
  t1e01: { name: "Replication Spore",     flavor: "A spore licensed for repair, not conquest; it copies only what the ecology can afford.",
    artifactForm: "Biotech Module / Fabrication Tool", blueprintRole: "controlled replication",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "adaptive biosphere civilization",
    engineeringScale: "Planetary", artPrompt: "Single engineered spore pod with cellular detail." },
  t1e02: { name: "Voidroot Tap",          flavor: "A root-tap that drinks from darkness without teaching the dark how to climb back up.",
    artifactForm: "Biotech Module / Interface", blueprintRole: "nutrient extraction from hidden reservoirs",
    blueprintFamilies: "Planetary Cradle Engine; Dark-Sector Observatory precursor", civLane: "subterranean adaptive life",
    engineeringScale: "Planetary", artPrompt: "Root-tap artifact entering black soil or void seam." },
  t1e03: { name: "Char Tendril",          flavor: "A blackened tendril that finds viable soil where ordinary roots only find a grave.",
    artifactForm: "Biotech Module / Sensor", blueprintRole: "post-fire ecological probing",
    blueprintFamilies: "Planetary Cradle Engine; Stellar Nursery Rite precursor", civLane: "fire-adapted ecology",
    engineeringScale: "Planetary", artPrompt: "Charred tendril with green ember tips." },
  t1e04: { name: "Climate Seed Die",      flavor: "A seed-die that prints the first organisms of a climate repair sequence, not the whole world.",
    artifactForm: "Fabrication Tool / Biotech Module", blueprintRole: "climate repair patterning",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "restorative biosphere civilization",
    engineeringScale: "Planetary", artPrompt: "Small die or seed-mold with micro-ecology pattern, no full planet." },
  t1e05: { name: "Facetcell Shard",       flavor: "A shard of living crystal whose cells decide what to become by how light breaks through them.",
    artifactForm: "Material / Biotech Module", blueprintRole: "cellular optical computation",
    blueprintFamilies: "Planetary Cradle Engine; Matrioshka Mind precursor", civLane: "crystalline cell ecology",
    engineeringScale: "Planetary", artPrompt: "Faceted organic shard with cellular inclusions." },
  t1e06: { name: "Decay Lattice",         flavor: "A living rule for decay, ensuring nothing dead becomes useless and nothing useful dies too soon.",
    artifactForm: "Biotech Module / Protocol", blueprintRole: "managed decomposition",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "recycler biosphere civilization",
    engineeringScale: "Planetary", artPrompt: "Small biological lattice digesting material with order." },
  t1e07: { name: "Lichen Vein",           flavor: "A vein of engineered lichen that teaches stone infrastructure how to heal at the edges.",
    artifactForm: "Biotech Module / Interface", blueprintRole: "stone-life integration",
    blueprintFamilies: "Ecumenopolis Lattice; Mantle-to-Orbit Foundry", civLane: "urban symbiosis civilization",
    engineeringScale: "Planetary", artPrompt: "Lichen vein embedded in metal/stone component." },
  t1e08: { name: "Necrobloom Bed",        flavor: "A cultivation bed where the dead are not raised, but recruited into the next repair cycle.",
    artifactForm: "Biotech Module / Archive", blueprintRole: "dead-biome reactivation",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "thanatological ecology",
    engineeringScale: "Planetary", artPrompt: "Cultivation tray/bed with pale blooms and fossil matter." },

  // ── Tier 1 ─ Abyss ───────────────────────────────────────────────────────
  t1o01: { name: "Entropy Veil",          flavor: "A veil that hides the heat and wear of a failing shelter long enough for repair crews to arrive.",
    artifactForm: "Defense / Shielding", blueprintRole: "decay masking",
    blueprintFamilies: "Worldshield Covenant; Heliopause Bastion precursor", civLane: "hidden-survival civilization",
    engineeringScale: "Planetary", artPrompt: "Dark translucent veil over small machine, subtle entropy particles." },
  t1o02: { name: "Horizon Lantern",       flavor: "A lantern tuned to edges, brightening near boundaries that should not yet be crossed.",
    artifactForm: "Sensor / Observatory", blueprintRole: "dangerous boundary detection",
    blueprintFamilies: "Dark-Sector Observatory precursor; Worldshield Covenant", civLane: "horizon observer culture",
    engineeringScale: "Planetary", artPrompt: "Black lantern with thin blue-white edge glow, no black hole vista." },
  t1o03: { name: "Ashen Hollow",          flavor: "A hollow vessel that preserves what the fire removed by remembering the shape of absence.",
    artifactForm: "Containment / Archive", blueprintRole: "absence preserving imprint",
    blueprintFamilies: "Worldshield Covenant; Spiral-Arm Archive precursor", civLane: "ash-memory civilization",
    engineeringScale: "Planetary", artPrompt: "Hollow dark vessel with ash contours." },
  t1o04: { name: "Undergrowth Silencer",  flavor: "A living silencer that lets buried networks communicate beneath the notice of predators.",
    artifactForm: "Defense / Concealment", blueprintRole: "biological noise suppression",
    blueprintFamilies: "Worldshield Covenant; Spiral Ecology Mesh precursor", civLane: "hidden root civilization",
    engineeringScale: "Planetary", artPrompt: "Compact rootlike muffler artifact, not a forest." },
  t1o05: { name: "Scorch-Erasure Seal",   flavor: "A seal applied after sanctioned fire, removing only traces that would endanger the innocent.",
    artifactForm: "Protocol / Containment", blueprintRole: "trace removal after ignition",
    blueprintFamilies: "Worldshield Covenant; Causality Audit Court precursor", civLane: "forensic shadow culture",
    engineeringScale: "Planetary", artPrompt: "Dark seal token with red ash halo." },
  t1o06: { name: "Decay Network",         flavor: "A hidden network that routes decay toward need, not merely downward into rot.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "distributed decomposition routing",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "subsurface recycler civilization",
    engineeringScale: "Planetary", artPrompt: "Small dark bio-network node, not entire web." },
  t1o07: { name: "Absence Shard",         flavor: "A shard measured by what it refuses to reflect; surveyors use it to map invisible load-bearing voids.",
    artifactForm: "Material / Sensor", blueprintRole: "negative-space reference material",
    blueprintFamilies: "Dark-Sector Observatory precursor; Worldshield Covenant", civLane: "absence mathematician culture",
    engineeringScale: "Planetary", artPrompt: "Dark shard with silhouette/reflection anomaly." },
  t1o08: { name: "Temporal Erasure Seal", flavor: "A redaction seal that hides a dangerous hour without deleting the lesson it should have taught.",
    artifactForm: "Protocol / Archive", blueprintRole: "limited record redaction",
    blueprintFamilies: "Causality Audit Court precursor; Worldshield Covenant", civLane: "protective secrecy civilization",
    engineeringScale: "Planetary", artPrompt: "Seal over clocklike shadow without text." },

  // ── Tier 1 ─ Radiance ────────────────────────────────────────────────────
  t1p01: { name: "Correction Seed",       flavor: "A seed that corrects the pattern before repair becomes mutation and law becomes punishment.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "error correction in growth or law",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "restorative civic biology",
    engineeringScale: "Planetary", artPrompt: "White-gold seed with geometric correction facets." },
  t1p02: { name: "Still-Point Shard",     flavor: "A shard used to hold one room, one reactor, or one treaty still while the world argues around it.",
    artifactForm: "Control Instrument / Stabilization", blueprintRole: "local equilibrium anchor",
    blueprintFamilies: "Worldshield Covenant; Causality Audit Court precursor", civLane: "equilibrium civic culture",
    engineeringScale: "Planetary", artPrompt: "White-gold shard suspending local motion." },
  t1p03: { name: "Prismatic Hollow",      flavor: "A hollow prism that separates signal from glamour before either can become policy.",
    artifactForm: "Interface / Sensor", blueprintRole: "truth-sorting aperture",
    blueprintFamilies: "Worldshield Covenant; Dark-Sector Observatory precursor", civLane: "revelatory optics civilization",
    engineeringScale: "Planetary", artPrompt: "Hollow prism/lens, solar white-gold refraction." },
  t1p04: { name: "Magnetic Bottle",       flavor: "A bottle made of discipline more than matter; it holds fire by persuading every field to agree.",
    artifactForm: "Containment / Power Component", blueprintRole: "plasma or field containment",
    blueprintFamilies: "Starlift Foundry precursor; Mantle-to-Orbit Foundry", civLane: "field-containment culture",
    engineeringScale: "Planetary", artPrompt: "Compact magnetic containment bottle with gold field lines." },
  t1p05: { name: "Recursive Lens",        flavor: "A lens that examines its own assumptions before it is trusted to examine the world.",
    artifactForm: "Sensor / Protocol", blueprintRole: "self-auditing perception",
    blueprintFamilies: "Causality Audit Court precursor; Matrioshka Mind precursor", civLane: "self-correcting optics culture",
    engineeringScale: "Planetary", artPrompt: "Lens with recursive reflections, no text." },
  t1p06: { name: "Living Lattice Node",   flavor: "A node that lets a living city coordinate repair without turning its citizens into machinery.",
    artifactForm: "Biotech Module / Civic Signal", blueprintRole: "living civic coordination node",
    blueprintFamilies: "Ecumenopolis Lattice; Galactic Concordance Engine precursor", civLane: "dense civic ecology",
    engineeringScale: "Planetary", artPrompt: "Small bio-civic node, luminous lattice close-up." },
  t1p07: { name: "Void Prism",            flavor: "A prism that makes darkness legible without pretending darkness has become safe.",
    artifactForm: "Sensor / Interface", blueprintRole: "illumination of hidden void states",
    blueprintFamilies: "Dark-Sector Observatory precursor; Worldshield Covenant", civLane: "hidden sun civilization",
    engineeringScale: "Planetary", artPrompt: "Prism showing black-violet interior and white-gold edges." },
  t1p08: { name: "Petrified Bloom",       flavor: "A stone flower used as proof that a living pattern can survive long after its garden cannot.",
    artifactForm: "Archive / Material", blueprintRole: "preserved life-pattern reference",
    blueprintFamilies: "Planetary Cradle Engine; Spiral-Arm Archive precursor", civLane: "fossil civic ecology",
    engineeringScale: "Planetary", artPrompt: "Fossil bloom in luminous stone, no label." },

  // ── Tier 2 ─ Flare ───────────────────────────────────────────────────────
  t2r01: { name: "Stellar Crucible",              flavor: "A crucible small enough to stand beside, fed by equations only a star-system economy can afford.",
    artifactForm: "Fabrication Tool / Containment", blueprintRole: "star-powered materials processing",
    blueprintFamilies: "Starlift Foundry; Galactic Relic Forge precursor", civLane: "stellar industrial civilization",
    engineeringScale: "Star-system", artPrompt: "Compact stellar crucible with contained star-material flow." },
  t2r02: { name: "Biomass Ignition Index",        flavor: "An index of ignition thresholds that lets habitats burn surplus biomass without burning their future.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "controlled bioenergy sequencing",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "star-fed biosphere culture",
    engineeringScale: "Star-system", artPrompt: "Data-like bioenergy index object, no text." },
  t2r03: { name: "Starlift Nozzle",               flavor: "A precision throat that turns star-plasma from apocalypse into supply chain.",
    artifactForm: "Control Instrument / Containment", blueprintRole: "stellar matter extraction",
    blueprintFamilies: "Starlift Foundry", civLane: "pressure-harvesting industrial civilization",
    engineeringScale: "Star-system", artPrompt: "Nozzle/throat component handling plasma stream, not full array." },
  t2r04: { name: "Photosynthetic Furnace Wick",   flavor: "A living furnace wick that lets cold ark-habitats carry a remembered sun between worlds.",
    artifactForm: "Biotech Module / Power Component", blueprintRole: "habitat-scale light-to-heat conversion",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "stellar greenhouse civilization",
    engineeringScale: "Star-system", artPrompt: "Living furnace wick inside habitat machinery, not a solar farm." },
  t2r05: { name: "Causality Furnace Valve",       flavor: "A furnace valve that opens only when the cost of power has been named in advance.",
    artifactForm: "Control Instrument / Protocol", blueprintRole: "controlled consequence release",
    blueprintFamilies: "Causality Audit Court precursor; Starlift Foundry", civLane: "causal-risk engineer civilization",
    engineeringScale: "Star-system", artPrompt: "Valve with red-blue causal flow, compact artifact." },
  t2r06: { name: "Entropy Sink Crucible",         flavor: "A sink-crucible that turns the insult of waste heat into one more useful argument for survival.",
    artifactForm: "Power Component / Thermal Control", blueprintRole: "waste heat capture",
    blueprintFamilies: "Dyson Swarm; Matrioshka Mind", civLane: "thermal accountant civilization",
    engineeringScale: "Star-system", artPrompt: "Thermal sink crucible with stellar glow, no whole star core." },

  // ── Tier 2 ─ Continuum ───────────────────────────────────────────────────
  t2s01: { name: "Interstice Gate Seed",          flavor: "A gate seed no larger than a hand, planted where routes may someday learn to open.",
    artifactForm: "Interface / Transit Component", blueprintRole: "gate-site initialization",
    blueprintFamilies: "Wormgate Spine precursor; Arkseed Migration Fleet", civLane: "route-planner civilization",
    engineeringScale: "Star-system", artPrompt: "Small aperture seed with blue spatial seam." },
  t2s02: { name: "Storm-Memory Filament",         flavor: "This thread remembers every solar storm it has survived, then warns the worlds before the next one learns their names.",
    artifactForm: "Archive / Sensor", blueprintRole: "stellar weather memory",
    blueprintFamilies: "Heliosphere Weather Loom; Matrioshka Mind", civLane: "heliosphere archivist culture",
    engineeringScale: "Star-system", artPrompt: "Fine filament with stored storm patterns." },
  t2s03: { name: "Simulation Loom",               flavor: "A loom that weaves possible years, then cuts the strands that demand too many graves.",
    artifactForm: "Fabrication Tool / Computation Substrate", blueprintRole: "predictive model weaving",
    blueprintFamilies: "Matrioshka Mind; Causality Audit Court precursor", civLane: "simulation guild civilization",
    engineeringScale: "Star-system", artPrompt: "Compact loom with simulated threads, no giant computer." },
  t2s04: { name: "Continuity Vessel",             flavor: "A vessel that keeps a people continuous when distance tries to make them merely related.",
    artifactForm: "Archive / Containment", blueprintRole: "identity continuity preservation",
    blueprintFamilies: "Arkseed Migration Fleet; Spiral-Arm Archive precursor", civLane: "migration memory civilization",
    engineeringScale: "Star-system", artPrompt: "Sealed vessel with memory light, no people portraits." },
  t2s05: { name: "Mnemosyne Star-Index",          flavor: "An index that lets every world remember the same disaster without agreeing on the same myth.",
    artifactForm: "Archive / Civic Signal Object", blueprintRole: "multi-world memory indexing",
    blueprintFamilies: "Matrioshka Mind; Spiral-Arm Archive precursor", civLane: "distributed archive civilization",
    engineeringScale: "Star-system", artPrompt: "Index shard/prism with star-map hints, no words." },
  t2s06: { name: "Convergence Lens",              flavor: "A lens that shows when different categories are being forced to pretend they were always one.",
    artifactForm: "Sensor / Interface", blueprintRole: "wildcard pressure inspection",
    blueprintFamilies: "Singularity Containment Mandala precursor; Causality Audit Court precursor", civLane: "convergence-risk civilization",
    engineeringScale: "Star-system", artPrompt: "Prismatic lens with white convergence glow, no purple Abyss dominance." },

  // ── Tier 2 ─ Verdance ────────────────────────────────────────────────────
  t2e01: { name: "Solar Immune Organ",      flavor: "Grown inside orbital habitats, it teaches living tissue which starlight to welcome and which to refuse.",
    artifactForm: "Biotech Module / Defense", blueprintRole: "radiation adaptation",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "multi-world biosphere civilization",
    engineeringScale: "Star-system", artPrompt: "Organ/graft with solar immune patterns, not a whole worldroot." },
  t2e02: { name: "Dormancy Clock Graft",    flavor: "A graft that lets a habitat sleep for centuries without forgetting when to wake hungry.",
    artifactForm: "Biotech Module / Archive", blueprintRole: "long-cycle dormancy timing",
    blueprintFamilies: "Arkseed Migration Fleet; Stellar Nursery Rite", civLane: "deep-time biological culture",
    engineeringScale: "Star-system", artPrompt: "Organic clock-graft, close-up component." },
  t2e03: { name: "Abyssal Culture Flask",   flavor: "A sealed flask of life trained to grow where sunlight is a rumor and pressure is weather.",
    artifactForm: "Biotech Module / Containment", blueprintRole: "dark-adapted culture growth",
    blueprintFamilies: "Heliopause Bastion; Spiral Ecology Mesh precursor", civLane: "dark-adapted biosphere culture",
    engineeringScale: "Star-system", artPrompt: "Dark bioflask with contained life, no full garden." },
  t2e04: { name: "Mycelial Relay Spindle",  flavor: "A spindle of engineered mycelium that translates between habitat, ship, soil, and silence.",
    artifactForm: "Interface / Biotech Module", blueprintRole: "interplanetary biological signaling",
    blueprintFamilies: "Arkseed Migration Fleet; Heliosphere Weather Loom", civLane: "symbiotic signal civilization",
    engineeringScale: "Star-system", artPrompt: "Mycelial spindle relay object, not huge network." },
  t2e05: { name: "Epoch Graft Ledger",      flavor: "A living ledger that changes tissue when an age ends, so the body learns history before the mind does.",
    artifactForm: "Archive / Biotech Module", blueprintRole: "biological era-tracking",
    blueprintFamilies: "Arkseed Migration Fleet; Spiral-Arm Archive precursor", civLane: "living chronology civilization",
    engineeringScale: "Star-system", artPrompt: "Biological ledger/graft with growth rings, no readable text." },
  t2e06: { name: "Crystal Biome Seedplate", flavor: "A seedplate that grows transparent habitats where crystal structure and living metabolism negotiate.",
    artifactForm: "Material / Biotech Module", blueprintRole: "crystal-organic habitat seeding",
    blueprintFamilies: "Heliosphere Weather Loom; Stellar Nursery Rite", civLane: "crystalline ecology civilization",
    engineeringScale: "Star-system", artPrompt: "Seedplate with crystalline cells, no full biome." },

  // ── Tier 2 ─ Abyss ───────────────────────────────────────────────────────
  t2o01: { name: "Horizon Extractor",         flavor: "An extractor that samples the edge of forbidden physics without inviting the edge inside.",
    artifactForm: "Sensor / Containment", blueprintRole: "boundary-energy sampling",
    blueprintFamilies: "Dark-Sector Observatory; Starlift Foundry", civLane: "horizon engineer civilization",
    engineeringScale: "Star-system", artPrompt: "Compact extractor at an abstract horizon edge, no full black hole." },
  t2o02: { name: "Radiant Erasure Casket",    flavor: "A casket for dangerous light, sealing revelations until public knowledge can survive them.",
    artifactForm: "Containment / Protocol", blueprintRole: "authorized signal deletion",
    blueprintFamilies: "Heliopause Bastion; Worldshield Covenant", civLane: "lawful redaction civilization",
    engineeringScale: "Star-system", artPrompt: "Small dark casket holding white-gold light." },
  t2o03: { name: "Entropic Furnace Baffle",   flavor: "A baffle that routes stellar waste into shadowed work instead of letting heat become confession.",
    artifactForm: "Thermal Control / Defense", blueprintRole: "entropy redirection",
    blueprintFamilies: "Starlift Foundry; Matrioshka Mind", civLane: "waste-heat shadow culture",
    engineeringScale: "Star-system", artPrompt: "Dark thermal baffle, no giant furnace." },
  t2o04: { name: "Extinction Forge Die",      flavor: "A die cast from failed worlds, used to make replacement parts for futures that nearly ended.",
    artifactForm: "Fabrication Tool / Archive", blueprintRole: "post-collapse reconstruction tooling",
    blueprintFamilies: "Galactic Relic Forge precursor; Spiral-Arm Archive precursor", civLane: "extinction-survivor culture",
    engineeringScale: "Star-system", artPrompt: "Small forge die with fossil/ash inclusions." },
  t2o05: { name: "Eventide Ecology Seal",     flavor: "A seal that lets an ecosystem go dark gracefully instead of collapsing into hunger.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "managed ecological shutdown",
    blueprintFamilies: "Heliosphere Weather Loom; Spiral Ecology Mesh precursor", civLane: "twilight ecology civilization",
    engineeringScale: "Star-system", artPrompt: "Seal over dim living pattern, twilight palette." },
  t2o06: { name: "Dimensional Shear Gauge",   flavor: "A gauge that measures when space is about to stop being infrastructure and start being injury.",
    artifactForm: "Sensor / Interface", blueprintRole: "boundary stress measurement",
    blueprintFamilies: "Heliopause Bastion; Wormgate Spine precursor", civLane: "spatial stress engineer civilization",
    engineeringScale: "Star-system", artPrompt: "Small gauge measuring a sliced spatial seam." },

  // ── Tier 2 ─ Radiance ────────────────────────────────────────────────────
  t2p01: { name: "Containment Lattice",       flavor: "A containment lattice built to be inspected by citizens, not merely trusted by engineers.",
    artifactForm: "Containment / Civic Signal", blueprintRole: "public-safe hazardous containment",
    blueprintFamilies: "Starlift Foundry; Singularity Containment Mandala precursor", civLane: "transparent containment civilization",
    engineeringScale: "Star-system", artPrompt: "White-gold containment module, not huge lattice." },
  t2p02: { name: "Null-Convergence Prism",    flavor: "A prism that brightens when too many meanings are being crushed into one convenient answer.",
    artifactForm: "Sensor / Interface", blueprintRole: "category collapse warning",
    blueprintFamilies: "Singularity Containment Mandala precursor; Matrioshka Mind", civLane: "convergence-auditing civilization",
    engineeringScale: "Star-system", artPrompt: "Prism/lens with white chromatic edges." },
  t2p03: { name: "Living Treaty Organ",       flavor: "An organ grown to hold agreements between worlds whose bodies disagree about what comfort means.",
    artifactForm: "Biotech Module / Civic Protocol", blueprintRole: "multi-world biological governance",
    blueprintFamilies: "Heliosphere Weather Loom; Galactic Concordance Engine precursor", civLane: "plural civic ecology",
    engineeringScale: "Star-system", artPrompt: "Living organ with geometric gold signal lines." },
  t2p04: { name: "Heliostat Filament",        flavor: "A single filament from a light-steering civilization; in the right orbit, it can teach mirrors to cooperate.",
    artifactForm: "Power Component / Signal Object", blueprintRole: "stellar light alignment",
    blueprintFamilies: "Dyson Swarm; Heliosphere Weather Loom", civLane: "solar coordination civilization",
    engineeringScale: "Star-system", artPrompt: "Fine gold-white filament, not full solar array." },
  t2p05: { name: "Error-Correcting Core",     flavor: "A core that spends more energy admitting mistakes than lesser machines spend pretending not to make them.",
    artifactForm: "Computation Substrate / Protocol", blueprintRole: "high-energy error correction",
    blueprintFamilies: "Matrioshka Mind; Causality Audit Court precursor", civLane: "precision computation civilization",
    engineeringScale: "Star-system", artPrompt: "Core with ordered correction geometry." },
  t2p06: { name: "Radiation Treaty Prism",    flavor: "A prism used to negotiate how much stellar danger each habitat agrees to bear for the others.",
    artifactForm: "Civic Signal / Sensor", blueprintRole: "shared radiation governance",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "multi-world biosphere treaty culture",
    engineeringScale: "Star-system", artPrompt: "Prism with habitat/radiation motifs, no text." },
};

// Tier 3 ── added separately so the file stays scannable
Object.assign(CARD_LORE, {
  // ── Tier 3 ─ Flare ─────────────────────────────────────────────────────
  t3r01: { name: "Relic Ignition Key",           flavor: "A key that starts machines no single star system could afford to misunderstand.",
    artifactForm: "Power Component / Interface", blueprintRole: "relic-scale activation",
    blueprintFamilies: "Galactic Relic Forge; Star-River Migration Lattice", civLane: "relic-making expansion civilization",
    engineeringScale: "Galactic", artPrompt: "Hand-sized ignition key with relic metal and controlled red-gold plasma." } as CardLore,
  t3r02: { name: "Extinction Furnace Veto",      flavor: "A veto token used when a civilization proves it can build an extinction furnace and chooses not to open it.",
    artifactForm: "Protocol / Control Instrument", blueprintRole: "civilization-ending energy veto",
    blueprintFamilies: "Causality Audit Court; Black-Map Pilgrimage Engine", civLane: "catastrophe-governance culture",
    engineeringScale: "Galactic", artPrompt: "Small veto seal/control token with dangerous furnace only as reflection." } as CardLore,
  t3r03: { name: "Temporal Burn Audit Lens",     flavor: "A lens that traces which histories were burned as fuel before the winning timeline called itself natural.",
    artifactForm: "Sensor / Protocol", blueprintRole: "timeline-energy risk audit",
    blueprintFamilies: "Causality Audit Court; Spiral-Arm Archive", civLane: "temporal hazard civilization",
    engineeringScale: "Galactic", artPrompt: "Lens with controlled fire-time traces, not giant event." } as CardLore,
  t3r04: { name: "Star-River Propulsion Core",   flavor: "A propulsion core calibrated for living habitats, powerful enough to move homes without turning them into cargo.",
    artifactForm: "Power Component / Biotech Interface", blueprintRole: "biosphere migration propulsion",
    blueprintFamilies: "Star-River Migration Lattice; Galactic Relic Forge", civLane: "living expansion civilization",
    engineeringScale: "Galactic", artPrompt: "Compact propulsion core with biological interfaces and red-green energy." } as CardLore,
  // ── Tier 3 ─ Continuum ─────────────────────────────────────────────────
  t3s01: { name: "Voidline Compass",             flavor: "It fits in one hand, but only a civilization with a galaxy of mistakes can read where it points.",
    artifactForm: "Transit Component / Sensor", blueprintRole: "hidden route detection",
    blueprintFamilies: "Wormgate Spine; Dark-Sector Observatory", civLane: "lawful hidden-transit civilization",
    engineeringScale: "Galactic", artPrompt: "Compass with voidline needle and subtle star-route hints." } as CardLore,
  t3s02: { name: "Recursion Witness Key",        flavor: "A key held by the witness, not the engineer, because recursion without testimony becomes tyranny.",
    artifactForm: "Protocol / Civic Signal", blueprintRole: "dangerous recursion authorization",
    blueprintFamilies: "Causality Audit Court; Spiral-Arm Archive", civLane: "legal-temporal civilization",
    engineeringScale: "Galactic", artPrompt: "Key/token with recursive geometry, no giant fire." } as CardLore,
  t3s03: { name: "Ancestor Signal Key",          flavor: "It unlocks messages sent by species that died before your star was named.",
    artifactForm: "Archive / Civic Signal", blueprintRole: "extinct-civilization handshake",
    blueprintFamilies: "Spiral-Arm Archive; Galactic Concordance Engine", civLane: "archivist civilization",
    engineeringScale: "Galactic", artPrompt: "Signal key/shard with fossil star-language motifs, no readable text." } as CardLore,
  t3s04: { name: "Chronology Governor",          flavor: "A governor for calendars that span species, relativistic routes, and wars over who gets to define before.",
    artifactForm: "Control Instrument / Protocol", blueprintRole: "galactic timeline governance",
    blueprintFamilies: "Causality Audit Court; Spiral-Arm Archive", civLane: "chronology-governing civilization",
    engineeringScale: "Galactic", artPrompt: "Precision governor object with time-map facets, no crown." } as CardLore,
  // ── Tier 3 ─ Verdance ──────────────────────────────────────────────────
  t3e01: { name: "Cryptobiotic Root Key",        flavor: "A root key that wakes only on worlds where the old biosphere left permission buried in the soil.",
    artifactForm: "Biotech Module / Transit Component", blueprintRole: "dormant biosphere routing",
    blueprintFamilies: "Spiral Ecology Mesh; Wormgate Spine", civLane: "hidden ancestral biosphere civilization",
    engineeringScale: "Galactic", artPrompt: "Small root key with dormant organic patterns, not giant roots." } as CardLore,
  t3e02: { name: "Ecology Substrate Code",       flavor: "A substrate code that lets unrelated biospheres share corridors without becoming one invasive species.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "galactic ecology compatibility",
    blueprintFamilies: "Spiral Ecology Mesh; Galactic Concordance Engine", civLane: "distributed ecology civilization",
    engineeringScale: "Galactic", artPrompt: "Code-like organic seed plate, no text letters." } as CardLore,
  t3e03: { name: "Ancestral Immune Code",        flavor: "An immune code written by extinct ecologies to protect living worlds from repeating their last appetite.",
    artifactForm: "Biotech Module / Archive", blueprintRole: "dead-lineage immune memory",
    blueprintFamilies: "Spiral Ecology Mesh; Spiral-Arm Archive", civLane: "ancestral necrobiome civilization",
    engineeringScale: "Galactic", artPrompt: "Organic code shard with fossil immune motifs." } as CardLore,
  t3e04: { name: "Plurality Charter Seed",       flavor: "A charter seed that grows different laws for different bodies without letting one species become the soil.",
    artifactForm: "Protocol / Biotech Module / Civic Signal", blueprintRole: "multi-species coexistence seed",
    blueprintFamilies: "Galactic Concordance Engine; Spiral Ecology Mesh", civLane: "plural civic ecology civilization",
    engineeringScale: "Galactic", artPrompt: "Seed/seal hybrid with many biological geometries, no crown." } as CardLore,
  // ── Tier 3 ─ Abyss ─────────────────────────────────────────────────────
  t3o01: { name: "Buried Biosphere Seal",        flavor: "A seal that keeps a biosphere dormant through centuries of discovery by civilizations too loud to trust.",
    artifactForm: "Defense / Biotech Module", blueprintRole: "hidden biosphere preservation",
    blueprintFamilies: "Spiral Ecology Mesh; Dark-Sector Observatory", civLane: "buried survival civilization",
    engineeringScale: "Galactic", artPrompt: "Small buried seal with dark root/biosphere hints, not full planet." } as CardLore,
  t3o02: { name: "Collapse Audit Mirror",        flavor: "A mirror that does not show ruin; it shows which safeguards were missing before anyone called ruin inevitable.",
    artifactForm: "Sensor / Protocol", blueprintRole: "collapse-risk reflection",
    blueprintFamilies: "Causality Audit Court; Singularity Containment Mandala", civLane: "collapse-auditing civilization",
    engineeringScale: "Galactic", artPrompt: "Dark mirror/lens with fractured ecological reflection." } as CardLore,
  t3o03: { name: "Silence Archive Shard",        flavor: "A shard that stores signals by hiding them so well that only the intended future can find them.",
    artifactForm: "Archive / Concealment", blueprintRole: "hidden signal preservation",
    blueprintFamilies: "Dark-Sector Observatory; Spiral-Arm Archive", civLane: "silent observer civilization",
    engineeringScale: "Galactic", artPrompt: "Black archive shard with faint sealed signal lines." } as CardLore,
  t3o04: { name: "Dark-Sector Aperture",         flavor: "An aperture into regions that maps cannot admit exist until a civilization is ready to be watched back.",
    artifactForm: "Interface / Sensor", blueprintRole: "forbidden-sector observation",
    blueprintFamilies: "Dark-Sector Observatory; Black-Map Pilgrimage Engine", civLane: "hidden observer civilization",
    engineeringScale: "Galactic", artPrompt: "Compact black aperture lens, no throne/crown imagery." } as CardLore,
  // ── Tier 3 ─ Radiance ──────────────────────────────────────────────────
  t3p01: { name: "Concordance Seal",             flavor: "No empire can counterfeit it; the seal only opens when rival species agree on what must not be owned.",
    artifactForm: "Protocol / Civic Signal Object", blueprintRole: "multi-species legitimacy",
    blueprintFamilies: "Galactic Concordance Engine; Causality Audit Court", civLane: "plural civic civilization",
    engineeringScale: "Galactic", artPrompt: "White-gold seal with void accents, no giant lattice." } as CardLore,
  t3p02: { name: "Public Maker-Seal",            flavor: "A maker-seal proving that an impossible artifact was built under law, not merely under power.",
    artifactForm: "Civic Signal / Fabrication Protocol", blueprintRole: "authorized relic manufacture",
    blueprintFamilies: "Galactic Relic Forge; Matrioshka Mind", civLane: "relic-making civic civilization",
    engineeringScale: "Galactic", artPrompt: "Small official maker-seal with computronium microtexture." } as CardLore,
  t3p03: { name: "Thermal Logic Wafer",          flavor: "A wafer of logic designed around waste heat, because even thought must answer for what it burns.",
    artifactForm: "Computation Substrate / Thermal Control", blueprintRole: "star-powered computation unit",
    blueprintFamilies: "Matrioshka Mind; Galactic Relic Forge", civLane: "nested computational archive civilization",
    engineeringScale: "Galactic", artPrompt: "Thin luminous wafer with nested thermal channels." } as CardLore,
  t3p04: { name: "Species-Rights Witness Prism", flavor: "A witness prism that records not who rules, but which kinds of beings were allowed to remain themselves.",
    artifactForm: "Civic Signal / Sensor", blueprintRole: "multi-species rights verification",
    blueprintFamilies: "Galactic Concordance Engine; Spiral-Arm Archive", civLane: "multi-species civic civilization",
    engineeringScale: "Galactic", artPrompt: "Prism witnessing multiple life-signatures, no crown or ruler figure." } as CardLore,
});

export function getCardLore(id: string): CardLore {
  return CARD_LORE[id] ?? { name: "Unnamed Artifact", flavor: "" };
}
