// ─── Luminae Card Lore ──────────────────────────────────────────────────────
// Names + flavor text sourced from LUMINAe_ARTIFACT_REPLACEMENT_TABLE_v0.4_UTILITY_FIRST_LORE.md
// Metadata fields (artifactForm, blueprintRole, blueprintFamilies, civLane,
// engineeringScale, artPrompt, practicalUse) also sourced from v0.4.
// Do NOT edit names, flavor, or metadata manually — update via the replacement table.
//
// artPrompt variety slots: see docs/card_art_variety_matrix.md
// Format: [Scale/Shot] — [Background] — [Subject] — [Palette] — [Exclusions]

export interface CardLore {
  name: string;
  flavor: string;
  practicalUse?: string;
  artifactForm?: string;
  blueprintRole?: string;
  blueprintFamilies?: string;
  civLane?: string;
  engineeringScale?: "Planetary" | "Star-system" | "Galactic";
  artPrompt?: string;
}

const CARD_LORE: Record<string, CardLore> = {
  // ── Tier 1 ─ Flare ───────────────────────────────────────────────────────
  t1r01: { name: "Ignition Kernel",       flavor: "A dense ignition core that can start a city, a shipyard, or a rescue furnace without becoming a weapon first.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Mantle-to-Orbit Foundry systems.",
    artifactForm: "Power Component / Control Instrument", blueprintRole: "controlled ignition and thermal regulation",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Planetary Cradle Engine", civLane: "planetary forge culture",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro cross-section view, abstract energy field background. Interior of a dense ignition core sliced open: layered rings of compressed red-orange plasma held in dark metal channels, glowing seams at the containment boundaries. Subject fills the frame — no exterior housing visible. Palette: deep red, molten orange, near-black metal. No planets, no text, no exterior structure." },

  t1r02: { name: "Ashroot Bloom",         flavor: "A fire-adapted root organ that turns disaster ash into the first useful tissue of recovery.",
    practicalUse: "Enables damaged habitats or biospheres to recover in support of Planetary Cradle Engine projects.",
    artifactForm: "Biotech Module / Catalyst", blueprintRole: "post-burn ecological recovery",
    blueprintFamilies: "Planetary Cradle Engine; Stellar Nursery Rite precursor", civLane: "phoenix biosphere",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, dark studio void background. A compact charred root organ — blackened surface with cracks revealing living ember veins beneath; two or three new pale-green shoots emerging from the ash-dusted base. Handheld scale, fills the frame. Palette: charcoal black, deep orange ember glow, pale green new growth. No planets, no text." },

  t1r03: { name: "Chrono-Ember Core",     flavor: "A warm memory-core that records when a fire should return, not merely how hot it burned.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Mantle-to-Orbit Foundry systems.",
    artifactForm: "Archive / Power Component", blueprintRole: "energy-memory synchronization",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Spiral-Arm Archive precursor", civLane: "deep-time ignition culture",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, soft atmospheric warm glow background. A palm-sized cylindrical memory-core with concentric time-ring etchings on its surface; amber ember light glows from the core's center, casting faint ring shadows. No giant clock, no star, no planet. Palette: warm amber, burnt orange, aged bronze metal. No baked-in text, labels, or title anywhere on the image." },

  t1r04: { name: "Causal Spark Coil",     flavor: "A trigger coil that refuses to fire unless the next three consequences remain survivable.",
    practicalUse: "Governs dangerous decisions or sequences so Mantle-to-Orbit Foundry systems can operate safely.",
    artifactForm: "Control Instrument / Protocol Object", blueprintRole: "safe trigger sequencing",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Causality Audit Court precursor", civLane: "experimental causal engineer civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A compact precision coil — tight wound copper-dark metal loops, three red-orange spark arcs suspended mid-air between the coil terminals, held in a precision housing with micro-engraved trigger markings. Handheld scale. Palette: deep red spark, dark metal, faint amber. No planets, no text." },

  t1r05: { name: "Voidflare Cask",        flavor: "A sealed cask that converts hidden pressure into one brief flare a city can survive.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Worldshield Covenant systems.",
    artifactForm: "Containment / Power Component", blueprintRole: "volatile void-pressure ignition",
    blueprintFamilies: "Worldshield Covenant; Mantle-to-Orbit Foundry", civLane: "eclipse host civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, dark studio void background. A sealed cylindrical cask — matte dark metal with a faint red-violet pressure glow seeping through stress fractures along the seam line; a small release valve on top is closed. Handheld scale, sitting on implied dark surface. Palette: near-black metal, red-violet pressure glow, subtle purple. No planets, no text." },

  t1r06: { name: "Photosynthetic Wick",   flavor: "A living wick that feeds on sunlight and releases heat slowly enough for a cold settlement to endure.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Planetary Cradle Engine systems.",
    artifactForm: "Biotech Module / Power Component", blueprintRole: "biological energy conversion",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "solar-adapted biosphere civilization",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, soft atmospheric warm glow background. A single living wick — a slender organic stalk, surface covered in fine amber-gold capillary channels that carry stored solar heat from tip to base; the tip glows softly with golden light. Fills the frame, handheld scale. Palette: warm amber, pale green cellular tissue, soft gold glow. No giant sun array, no planets, no text." },

  t1r07: { name: "Entropy Pyre Baffle",   flavor: "A heat baffle that teaches waste where to go before it teaches the city how to die.",
    practicalUse: "Holds hazardous forces in usable form for Mantle-to-Orbit Foundry systems.",
    artifactForm: "Containment / Thermal Control", blueprintRole: "waste heat and decay routing",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Worldshield Covenant", civLane: "entropy-tolerant industrial culture",
    engineeringScale: "Planetary",
    artPrompt: "Installation-scale eye-level view, abstract energy distortion background — industrial heat shimmer. A massive facade of heat-sink baffle panels covering the side of a facility: dark containment fins span the full height of the building, surfaces blackened with soot and oxidation; deep orange-red glows pour from the channel voids where waste heat streams through. The baffle wall fills the entire frame. Palette: dark steel, soot grey, deep orange heat glow. No planets, no text." },

  t1r08: { name: "Oathfire Igniter",      flavor: "An igniter that only opens in the presence of witnesses, making fire a civic act instead of a private threat.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Worldshield Covenant systems.",
    artifactForm: "Civic Signal Object / Power Component", blueprintRole: "public sanctioned ignition",
    blueprintFamilies: "Worldshield Covenant; Ecumenopolis Lattice", civLane: "solar civic forge culture",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop worm's-eye view (looking slightly upward), soft atmospheric warm glow background. A ceremonial ignition tool held upright — ornate gold-and-dark-metal body with a witness-lock mechanism visible on the grip; a restrained red-gold flame emerges from the tip. Viewed from slightly below, giving the tool civic authority. Palette: gold, deep red flame, dark forged metal. No text, no giant structure." },

  // ── Tier 1 ─ Continuum ───────────────────────────────────────────────────
  t1s01: { name: "Echo Splinter",         flavor: "A broken sliver of recorded cause, useful because it remembers the sound before the disaster.",
    practicalUse: "Reveals dangerous states early so Spiral-Arm Archive precursor systems can be corrected before failure.",
    artifactForm: "Archive / Sensor", blueprintRole: "event echo capture",
    blueprintFamilies: "Spiral-Arm Archive precursor; Worldshield Covenant", civLane: "planetary memory culture",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, dark studio void background. A slim sapphire-blue crystal splinter — fractured end shows a layered internal structure; faint concentric echo rings radiate outward from the break point, visible as subtle refractive bands within the crystal. Fills the frame, finger-length scale. Palette: sapphire blue, pale ice refraction, near-black void. No planets, no text." },

  t1s02: { name: "Causal Ember Relay",    flavor: "A relay that passes heat, signal, and consequence in the same controlled pulse.",
    practicalUse: "Functions as a specialized interface / protocol for Mantle-to-Orbit Foundry projects.",
    artifactForm: "Interface / Protocol", blueprintRole: "local cause-effect relay",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Causality Audit Court precursor", civLane: "predictive engineering culture",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, soft atmospheric warm glow background. A small relay node — dark metal housing with amber-blue causal trace lines etched on its surface, glowing where heat and signal pulses converge at the relay junction. Coin-sized scale, fills the frame. Palette: amber warm, sapphire blue causal traces, dark metal body. No planets, no text." },

  t1s03: { name: "Null-Loop Anchor",      flavor: "An anchor that ends a loop before a city mistakes repetition for immortality.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Worldshield Covenant operations.",
    artifactForm: "Control Instrument / Stabilization", blueprintRole: "recursion boundary control",
    blueprintFamilies: "Worldshield Covenant; Causality Audit Court precursor", civLane: "recursion-safety civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, abstract energy field background with faint recursive interference pattern. A compact anchor ring — dark blue-black metal forged in a closed ring; the inner surface is etched with recursive boundary markings that glow faintly blue where the loop-end sequence is engaged. Handheld scale. Palette: deep blue, near-black metal, faint recursion-glow lines. No planets, no readable text on the anchor." },

  t1s04: { name: "Time-Crystal Scaffold", flavor: "A scaffold grown from timing crystals, used wherever machines must agree on the same second.",
    practicalUse: "Manufactures or patterns specialized components needed by Ecumenopolis Lattice projects.",
    artifactForm: "Material / Fabrication Tool", blueprintRole: "precision timing substrate",
    blueprintFamilies: "Ecumenopolis Lattice; Matrioshka Mind precursor", civLane: "timekeeping material culture",
    engineeringScale: "Planetary",
    artPrompt: "Installation-scale eye-level view, soft atmospheric cool glow background. A timing-crystal scaffold filling a warehouse interior: grown rather than built, the branching blue-white crystal lattice rises from floor to ceiling and spans wall to wall; fine blue synchronization pulses move between crystal nodes across the entire structure. The scaffold fills the frame completely. Palette: ice blue, pale crystal white, cool atmospheric glow. No planets, no text." },

  t1s05: { name: "Silent Recursion Rule", flavor: "A recursion rule copied in silence because speaking it aloud changes the system it protects.",
    practicalUse: "Functions as a specialized protocol / archive for Matrioshka Mind precursor projects.",
    artifactForm: "Protocol / Archive", blueprintRole: "quiet error correction",
    blueprintFamilies: "Matrioshka Mind precursor; Worldshield Covenant", civLane: "quiet planner civilization",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, mineral/rock surface background — dark polished stone. A small etched protocol token or wafer — deep blue-black material with concentric recursion geometry incised on its face; the etchings glow faintly blue, catching light at their edges. Coin-sized scale. Palette: deep blue, near-black, faint cool recursion glow. No readable text, no letters or numerals anywhere on the token surface." },

  t1s06: { name: "Living Chronicle",      flavor: "A chronicle that grows new margins when the people it records learn to become someone else.",
    practicalUse: "Stores, indexes, or releases critical memory for Planetary Cradle Engine infrastructure.",
    artifactForm: "Archive / Biotech Module", blueprintRole: "adaptive civic memory",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "biological archive civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, dark studio void background. A compact organic memory organ — resembles a thick living book whose cover is grown tissue rather than leather; blue-green veins run through the surface, pulsing faintly with stored memory light; new pale margin-tissue is budding at the edges. Handheld scale. Palette: blue-green veins, pale organic tissue, warm glow interior. No letters, no text on the surface." },

  t1s07: { name: "String-Scar Loom",      flavor: "A loom that turns flaws in exotic threads into repeatable manufacturing instructions.",
    practicalUse: "Manufactures or patterns specialized components needed by Mantle-to-Orbit Foundry projects.",
    artifactForm: "Fabrication Tool / Material", blueprintRole: "defect-pattern weaving",
    blueprintFamilies: "Mantle-to-Orbit Foundry; Galactic Relic Forge precursor", civLane: "defect-engineer culture",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A small precision loom — dark metal frame with luminous sapphire-blue tension threads strung across it; the threads glow where deliberate defect-nodes are locked in place as encoded manufacturing instructions. Handheld scale, sits on a dark surface. Palette: deep blue luminous threads, dark metal frame, cool sapphire light. No planets, no text." },

  t1s08: { name: "Root Memory Valve",     flavor: "A valve grown into old roots, opening only enough ancestral memory for the present to survive.",
    practicalUse: "Stores, indexes, or releases critical memory for Planetary Cradle Engine infrastructure.",
    artifactForm: "Archive / Biotech Module / Control Instrument", blueprintRole: "selective memory release",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "ancestral biosphere civilization",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro cross-section view, mineral/rock surface background — dark ancient wood-grain soil. Interior of a root-valve sliced open: the valve mechanism is grown into the root tissue, blue-green memory glow visible in the chambers that control what ancestral signals are released. Fills the frame. Palette: dark root tissue, blue-green memory light, soil texture. No giant forest, no planets, no text." },

  // ── Tier 1 ─ Verdance ────────────────────────────────────────────────────
  t1e01: { name: "Replication Spore",     flavor: "A spore licensed for repair, not conquest; it copies only what the ecology can afford.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Biotech Module / Fabrication Tool", blueprintRole: "controlled replication",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "adaptive biosphere civilization",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, mineral/rock surface background — mossy dark stone. A single engineered spore pod resting on the stone — ovoid, translucent green-white casing with detailed cellular structure visible inside; hairlike anchor filaments extend from the base. Grain-of-rice scale. Palette: pale green, translucent cellular white, dark stone surface. No planets, no cosmic scene, no text." },

  t1e02: { name: "Voidroot Tap",          flavor: "A root-tap that drinks from darkness without teaching the dark how to climb back up.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Planetary Cradle Engine operations.",
    artifactForm: "Biotech Module / Interface", blueprintRole: "nutrient extraction from hidden reservoirs",
    blueprintFamilies: "Planetary Cradle Engine; Dark-Sector Observatory precursor", civLane: "subterranean adaptive life",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, mineral/rock surface background — black soil and void-seam crack. A root-tap artifact pressing into the seam: the upper portion is a dark engineered fitting; below it, biological root-material descends into the void-black crack, dark green with bioluminescent veins. Handheld device scale. Palette: dark green, near-black void, faint bioluminescent blue-green. No planets, no text." },

  t1e03: { name: "Char Tendril",          flavor: "A blackened tendril that finds viable soil where ordinary roots only find a grave.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Biotech Module / Sensor", blueprintRole: "post-fire ecological probing",
    blueprintFamilies: "Planetary Cradle Engine; Stellar Nursery Rite precursor", civLane: "fire-adapted ecology",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro worm's-eye view (looking up along the tendril), soft atmospheric warm-green glow background. A charred tendril arching upward — blackened and cracked surface, two small ember-tipped probe nodes at the top glowing green-amber, testing the air above ash. Fills the frame from base to tip. Palette: charcoal black, green ember tips, warm ash-glow. No planets, no giant organic structure, no text." },

  t1e04: { name: "Climate Seed Die",      flavor: "A seed-die that prints the first organisms of a climate repair sequence, not the whole world.",
    practicalUse: "Enables damaged habitats or biospheres to recover in support of Planetary Cradle Engine projects.",
    artifactForm: "Fabrication Tool / Biotech Module", blueprintRole: "climate repair patterning",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "restorative biosphere civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A small fabrication die — cube-shaped, dark metal, each face bearing a different micro-ecology pattern in fine relief; tiny root and cell motifs etched across the surfaces catch cool green light. Fingertip-sized. Palette: dark metal, cool green, pale cellular detail. No full planet, no space, no text." },

  t1e05: { name: "Facetcell Shard",       flavor: "A shard of living crystal whose cells decide what to become by how light breaks through them.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Material / Biotech Module", blueprintRole: "cellular optical computation",
    blueprintFamilies: "Planetary Cradle Engine; Matrioshka Mind precursor", civLane: "crystalline cell ecology",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, dark studio void background. A faceted organic crystal shard — translucent green-white, with clearly visible cellular inclusions visible through the facet planes; prismatic light breaks across the faces in pale green and teal. Fills the frame. Palette: living green, translucent crystal, pale cellular inclusions, cool teal refraction. No planets, no text." },

  t1e06: { name: "Decay Lattice",         flavor: "A living rule for decay, ensuring nothing dead becomes useless and nothing useful dies too soon.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Biotech Module / Protocol", blueprintRole: "managed decomposition",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "recycler biosphere civilization",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro cross-section view, mineral/rock surface background — dark loam and decomposing matter. A small biological lattice sliced open: a grid of living filaments in an ordered decomposition matrix, dark green with pale nutrient channels visible at the junctions. Thumbnail-sized scale, fills the frame. Palette: dark green, pale nutrient-channel light, rich dark loam. No planets, no giant organism, no text." },

  t1e07: { name: "Lichen Vein",           flavor: "A vein of engineered lichen that teaches stone infrastructure how to heal at the edges.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Ecumenopolis Lattice projects.",
    artifactForm: "Biotech Module / Interface", blueprintRole: "stone-life integration",
    blueprintFamilies: "Ecumenopolis Lattice; Mantle-to-Orbit Foundry", civLane: "urban symbiosis civilization",
    engineeringScale: "Planetary",
    artPrompt: "Installation-scale eye-level view, mineral/rock surface background — massive stone and metal facade. A lichen vein colony covering an entire building-wall face: vivid living green tissue spreading in a branching pattern across many meters of engineered stone and metal; the active healing interface glows faint bioluminescent green along its advancing edge, visible at eye level. The wall fills the entire frame. Palette: deep green lichen, grey stone, dark metal, faint bioluminescent healing edge. No planets, no text." },

  t1e08: { name: "Necrobloom Bed",        flavor: "A cultivation bed where the dead are not raised, but recruited into the next repair cycle.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Biotech Module / Archive", blueprintRole: "dead-biome reactivation",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "thanatological ecology",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, dark studio void background. A shallow cultivation tray sitting on a dark surface — holds a bed of grey fossil matter and pale soil; three small pale blooms with faintly luminous petals emerge from the bed, their roots visibly threading through fossilized material. Tray is roughly hand-sized. Palette: pale bloom white, grey fossil, dark soil, faint green-white bioluminescence. No planets, no giant scene, no text." },

  // ── Tier 1 ─ Abyss ───────────────────────────────────────────────────────
  t1o01: { name: "Entropy Veil",          flavor: "A veil that hides the heat and wear of a failing shelter long enough for repair crews to arrive.",
    practicalUse: "Functions as a specialized defense / shielding for Worldshield Covenant projects.",
    artifactForm: "Defense / Shielding", blueprintRole: "decay masking",
    blueprintFamilies: "Worldshield Covenant; Heliopause Bastion precursor", civLane: "hidden-survival civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, soft atmospheric cool glow background — faint purple ambient light. A translucent dark veil draped over a small machine component; the veil is near-invisible but causes the machine beneath it to appear slightly out-of-focus, entropy particles drifting near its edges like slow motes. Handheld scale. Palette: dark translucent purple-black, faint particle motes, dim purple ambient. No planets, no full black hole, no text." },

  t1o02: { name: "Horizon Lantern",       flavor: "A lantern tuned to edges, brightening near boundaries that should not yet be crossed.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Dark-Sector Observatory precursor operations.",
    artifactForm: "Sensor / Observatory", blueprintRole: "dangerous boundary detection",
    blueprintFamilies: "Dark-Sector Observatory precursor; Worldshield Covenant", civLane: "horizon observer culture",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, dark studio void background. A compact black-metal lantern with a sealed housing; along every edge and seam of the lantern's body a thin blue-white glow indicates proximity to a dangerous boundary. The lens is dark at rest. Handheld scale, sits upright. Palette: matte black metal, thin blue-white edge glow at seams, near-void background. No planets, no black hole vista, no text." },

  t1o03: { name: "Ashen Hollow",          flavor: "A hollow vessel that preserves what the fire removed by remembering the shape of absence.",
    practicalUse: "Holds hazardous forces in usable form for Worldshield Covenant systems.",
    artifactForm: "Containment / Archive", blueprintRole: "absence preserving imprint",
    blueprintFamilies: "Worldshield Covenant; Spiral-Arm Archive precursor", civLane: "ash-memory civilization",
    engineeringScale: "Planetary",
    artPrompt: "Room-scale cross-section view, dark studio void background. Interior of a hollow archive vessel shown in cutaway — the inner walls carry precise ash-contour relief maps of objects that were destroyed; a faint negative-space glow traces the absent forms. The vessel's interior fills the frame. Palette: ash grey, deep black walls, faint pale contour glow. No planets, no crater imagery, no text." },

  t1o04: { name: "Undergrowth Silencer",  flavor: "A living silencer that lets buried networks communicate beneath the notice of predators.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Worldshield Covenant projects.",
    artifactForm: "Defense / Concealment", blueprintRole: "biological noise suppression",
    blueprintFamilies: "Worldshield Covenant; Spiral Ecology Mesh precursor", civLane: "hidden root civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop macro close-up, mineral/rock surface background — dark loam and root debris. A compact rootlike muffler artifact — dense organic material wound around a dark core; the surface absorbs light, giving it a near-matte appearance; thin root filaments extend outward to anchor it in soil. Walnut-sized. Palette: near-black root mass, dark earth tones, faint dark-green filaments. No full forest, no planets, no text." },

  t1o05: { name: "Scorch-Erasure Seal",   flavor: "A seal applied after sanctioned fire, removing only traces that would endanger the innocent.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Worldshield Covenant systems.",
    artifactForm: "Protocol / Containment", blueprintRole: "trace removal after ignition",
    blueprintFamilies: "Worldshield Covenant; Causality Audit Court precursor", civLane: "forensic shadow culture",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, abstract energy field background — dark with faint red distortion waves. A flat dark seal token with a faint halo of red ash particles drifting around its perimeter; the seal's face is smooth with a single circular redaction mark pressed into its center. Coin-sized scale, fills the frame. Palette: near-black seal, deep red ash halo, dark energy distortion. No planets, no text or letters on the seal face." },

  t1o06: { name: "Decay Network",         flavor: "A hidden network that routes decay toward need, not merely downward into rot.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "distributed decomposition routing",
    blueprintFamilies: "Planetary Cradle Engine; Spiral Ecology Mesh precursor", civLane: "subsurface recycler civilization",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro cross-section view, mineral/rock surface background — dark soil and substrate. A single dark bio-network node sliced open: inside, branching routing channels direct decay matter toward collecting chambers; the junction glows faint green-purple where active decomposition routing is occurring. Marble-sized scale, fills the frame. Palette: near-black node body, dark soil, faint green-purple junction glow. No full network visible, no planets, no text." },

  t1o07: { name: "Absence Shard",         flavor: "A shard measured by what it refuses to reflect; surveyors use it to map invisible load-bearing voids.",
    practicalUse: "Reveals dangerous states early so Dark-Sector Observatory precursor systems can be corrected before failure.",
    artifactForm: "Material / Sensor", blueprintRole: "negative-space reference material",
    blueprintFamilies: "Dark-Sector Observatory precursor; Worldshield Covenant", civLane: "absence mathematician culture",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, dark studio void background. A dark shard — deep black-grey material with a polished face that shows an anomalous negative-space reflection: where other objects would reflect, the shard reflects only its own absence. One edge catches faint pale light while the rest absorbs completely. Finger-length scale, fills the frame. Palette: near-black, charcoal grey facets, pale edge light. No planets, no text." },

  t1o08: { name: "Temporal Erasure Seal", flavor: "A redaction seal that hides a dangerous hour without deleting the lesson it should have taught.",
    practicalUse: "Functions as a specialized protocol / archive for Causality Audit Court precursor projects.",
    artifactForm: "Protocol / Archive", blueprintRole: "limited record redaction",
    blueprintFamilies: "Causality Audit Court precursor; Worldshield Covenant", civLane: "protective secrecy civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A flat dark disc seal placed over a clocklike shadow — beneath the seal, the impression of a clock or temporal record is just visible as a ghost image in the surface; the seal itself is smooth, authoritative, without writing. Palm-sized scale. Palette: near-black seal, dark shadow clock beneath, deep grey. No text, no numbers visible anywhere." },

  // ── Tier 1 ─ Radiance ────────────────────────────────────────────────────
  t1p01: { name: "Correction Seed",       flavor: "A seed that corrects the pattern before repair becomes mutation and law becomes punishment.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Planetary Cradle Engine projects.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "error correction in growth or law",
    blueprintFamilies: "Planetary Cradle Engine; Ecumenopolis Lattice", civLane: "restorative civic biology",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, dark studio void background. A single white-gold seed with precise geometric correction facets on its casing — not organic, but architecturally exact; each facet plane catches warm gold light differently, giving the seed a jewel-like precision. Grain-of-wheat scale, fills the frame. Palette: white-gold, warm gold facet light, pure black void. No planets, no text." },

  t1p02: { name: "Still-Point Shard",     flavor: "A shard used to hold one room, one reactor, or one treaty still while the world argues around it.",
    practicalUse: "Functions as a specialized control instrument / stabilization for Worldshield Covenant projects.",
    artifactForm: "Control Instrument / Stabilization", blueprintRole: "local equilibrium anchor",
    blueprintFamilies: "Worldshield Covenant; Causality Audit Court precursor", civLane: "equilibrium civic culture",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, abstract energy field background — faint white distortion waves suspended motionless. A white-gold crystal shard that appears to be suspending local motion: the energy field around it is frozen in place, forming a small zone of perfect stillness around the shard's surface. Finger-length scale, fills the frame. Palette: white-gold crystal, pale distortion freeze, luminous white field. No planets, no baked-in text or labels anywhere in the image." },

  t1p03: { name: "Prismatic Hollow",      flavor: "A hollow prism that separates signal from glamour before either can become policy.",
    practicalUse: "Reveals dangerous states early so Worldshield Covenant systems can be corrected before failure.",
    artifactForm: "Interface / Sensor", blueprintRole: "truth-sorting aperture",
    blueprintFamilies: "Worldshield Covenant; Dark-Sector Observatory precursor", civLane: "revelatory optics civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, soft atmospheric warm-gold glow background. A hollow prism — white-gold glass, visible cavity at its center; light entering one face is refracted and split, with pure signal-wavelengths emerging from one face and glamour-wavelengths blocked. Solar white-gold refraction fills the glass body. Handheld scale. Palette: white-gold, warm solar refraction, soft atmospheric glow. No planets, no giant megastructure, no text." },

  t1p04: { name: "Magnetic Bottle",       flavor: "A bottle made of discipline more than matter; it holds fire by persuading every field to agree.",
    practicalUse: "Holds hazardous forces in usable form for Starlift Foundry precursor systems.",
    artifactForm: "Containment / Power Component", blueprintRole: "plasma or field containment",
    blueprintFamilies: "Starlift Foundry precursor; Mantle-to-Orbit Foundry", civLane: "field-containment culture",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A compact magnetic containment bottle — spherical-ovoid form in white-gold metal; visible gold magnetic field lines curve around the exterior like latitude lines, converging at the poles; a faint warm plasma glow is just visible through the translucent equatorial band. Handheld scale. Palette: white-gold metal, luminous gold field lines, warm plasma interior glow. No planets, no text." },

  t1p05: { name: "Recursive Lens",        flavor: "A lens that examines its own assumptions before it is trusted to examine the world.",
    practicalUse: "Reveals dangerous states early so Causality Audit Court precursor systems can be corrected before failure.",
    artifactForm: "Sensor / Protocol", blueprintRole: "self-auditing perception",
    blueprintFamilies: "Causality Audit Court precursor; Matrioshka Mind precursor", civLane: "self-correcting optics culture",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop eye-level view, dark studio void background. A circular white-gold lens in a precision housing; the lens surface shows recursive reflections of itself — smaller and smaller versions of the same lens visible in its center, catching the same white-gold light. Handheld scale, sits upright. Palette: white-gold, luminous recursive reflection geometry, dark void. No text, no labels." },

  t1p06: { name: "Living Lattice Node",   flavor: "A node that lets a living city coordinate repair without turning its citizens into machinery.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Ecumenopolis Lattice projects.",
    artifactForm: "Biotech Module / Civic Signal", blueprintRole: "living civic coordination node",
    blueprintFamilies: "Ecumenopolis Lattice; Galactic Concordance Engine precursor", civLane: "dense civic ecology",
    engineeringScale: "Planetary",
    artPrompt: "Extreme macro close-up, soft atmospheric warm-gold glow background. A small bio-civic coordination node — organic material at its core with geometric gold lattice extensions radiating outward like a living circuit; the lattice glows warm white-gold at each junction point. Fills the frame, marble-sized scale. Palette: warm white-gold lattice, living cream-tissue core, soft gold atmospheric glow. No planets, no text." },

  t1p07: { name: "Void Prism",            flavor: "A prism that makes darkness legible without pretending darkness has become safe.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Dark-Sector Observatory precursor operations.",
    artifactForm: "Sensor / Interface", blueprintRole: "illumination of hidden void states",
    blueprintFamilies: "Dark-Sector Observatory precursor; Worldshield Covenant", civLane: "hidden sun civilization",
    engineeringScale: "Planetary",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, abstract energy field background — dark with white-gold energy distortion. A prism with a black-violet interior: light entering from one face is converted to a readable void-state spectrum exiting from another; white-gold edge lines define the prism geometry against the dark interior. Handheld scale. Palette: black-violet interior, white-gold edges, dark energy field. No planets, no text." },

  t1p08: { name: "Petrified Bloom",       flavor: "A stone flower used as proof that a living pattern can survive long after its garden cannot.",
    practicalUse: "Functions as a specialized archive / material for Planetary Cradle Engine projects.",
    artifactForm: "Archive / Material", blueprintRole: "preserved life-pattern reference",
    blueprintFamilies: "Planetary Cradle Engine; Spiral-Arm Archive precursor", civLane: "fossil civic ecology",
    engineeringScale: "Planetary",
    artPrompt: "Installation-scale eye-level view, mineral/rock surface background — cliff face of luminous pale stone. A fossil bloom preserved in a cliff-wall several meters across: the flower's petals are rendered in white-gold mineral at architectural scale, their light-catching facets visible from a distance; faint bioluminescent veins still active in the surrounding stone trace the outline of a garden long gone. The cliff face fills the frame. Palette: white-gold fossil bloom, warm pale stone cliff, faint living-vein glow. No text, no labels." },

  // ── Tier 2 ─ Flare ───────────────────────────────────────────────────────
  t2r01: { name: "Stellar Crucible",              flavor: "A crucible small enough to stand beside, fed by equations only a star-system economy can afford.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Starlift Foundry systems.",
    artifactForm: "Fabrication Tool / Containment", blueprintRole: "star-powered materials processing",
    blueprintFamilies: "Starlift Foundry; Galactic Relic Forge precursor", civLane: "stellar industrial civilization",
    engineeringScale: "Star-system",
    artPrompt: "Room-scale eye-level view, abstract energy distortion background — rippling red-gold plasma interference. A stellar crucible standing at human height — squat cylindrical refractory vessel with star-material flow entering through an upper port: a contained stream of compressed solar plasma flows down into the melt chamber, visible through a reinforced observation slit. Palette: deep red, molten gold, dark refractory metal. No full star, no planets, no text." },

  t2r02: { name: "Biomass Ignition Index",        flavor: "An index of ignition thresholds that lets habitats burn surplus biomass without burning their future.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Heliosphere Weather Loom systems.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "controlled bioenergy sequencing",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "star-fed biosphere culture",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A protocol index object — a compact layered disc or tablet of biopolymer and dark metal, its surface bearing a radial arrangement of ignition-threshold markings etched in relief (geometric, not text). Biomass sample chambers are visible as small sealed cells around the perimeter. Handheld scale. Palette: warm red-orange accents, dark biopolymer, deep green biomass cells. No text or labels." },

  t2r03: { name: "Starlift Nozzle",               flavor: "A precision throat that turns star-plasma from apocalypse into supply chain.",
    practicalUse: "Holds hazardous forces in usable form for Starlift Foundry systems.",
    artifactForm: "Control Instrument / Containment", blueprintRole: "stellar matter extraction",
    blueprintFamilies: "Starlift Foundry", civLane: "pressure-harvesting industrial civilization",
    engineeringScale: "Star-system",
    artPrompt: "Installation-scale cross-section view, abstract energy field background — red-orange plasma shimmer. A massive starlift nozzle throat in cross-section: the convergent-divergent channel geometry spans a space large enough to walk through; inner walls are dark refractory alloy with cooling fins, compressed star-plasma flowing through the throat as a bright controlled stream filling the center. The cross-section fills the frame. Palette: dark alloy walls, contained red-gold plasma stream, heat-glow orange. No text." },

  t2r04: { name: "Photosynthetic Furnace Wick",   flavor: "A living furnace wick that lets cold ark-habitats carry a remembered sun between worlds.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Heliosphere Weather Loom projects.",
    artifactForm: "Biotech Module / Power Component", blueprintRole: "habitat-scale light-to-heat conversion",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "stellar greenhouse civilization",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop eye-level view, soft atmospheric warm glow background. A living furnace wick fitted into habitat machinery: an organic stalk held in a dark metal mount, its tissue dense with amber-gold photosynthetic capillaries; the wick glows with stored solar heat, warming the metal bracket that holds it inside a habitat wall cavity. Handheld component scale. Palette: warm amber, living green-gold capillaries, dark metal mount. No solar farm, no planets, no text." },

  t2r05: { name: "Causality Furnace Valve",       flavor: "A furnace valve that opens only when the cost of power has been named in advance.",
    practicalUse: "Functions as a specialized control instrument / protocol for Causality Audit Court precursor projects.",
    artifactForm: "Control Instrument / Protocol", blueprintRole: "controlled consequence release",
    blueprintFamilies: "Causality Audit Court precursor; Starlift Foundry", civLane: "causal-risk engineer civilization",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, abstract energy field background — red and blue causal interference ripple. A compact furnace valve with a split-flow design: one side channels red heat flow, the other channels blue causal-lock signal; the valve seat is visible at center, closed until both flows agree. Coin-sized mechanism scale, fills the frame. Palette: deep red heat channel, sapphire blue causal lock, dark metal body. No full furnace, no planets, no text." },

  t2r06: { name: "Entropy Sink Crucible",         flavor: "A sink-crucible that turns the insult of waste heat into one more useful argument for survival.",
    practicalUse: "Functions as a specialized power component / thermal control for Dyson Swarm projects.",
    artifactForm: "Power Component / Thermal Control", blueprintRole: "waste heat capture",
    blueprintFamilies: "Dyson Swarm; Matrioshka Mind", civLane: "thermal accountant civilization",
    engineeringScale: "Star-system",
    artPrompt: "Planetary-scale eye-level view, planetary backdrop background — planet surface and terminator line visible. The entropy sink crucible as a planetary installation: a massive dark thermal-ceramic tower complex visible against a planet's terminator line; orange-red heat glow from the upper collection manifolds illuminates the surrounding dark surface; the scale dwarfs any city. Palette: dark thermal-ceramic, deep orange heat glow, planet surface and atmospheric limb. No text." },

  // ── Tier 2 ─ Continuum ───────────────────────────────────────────────────
  t2s01: { name: "Interstice Gate Seed",          flavor: "A gate seed no larger than a hand, planted where routes may someday learn to open.",
    practicalUse: "Supports safe movement, routing, or migration within Wormgate Spine precursor infrastructure.",
    artifactForm: "Interface / Transit Component", blueprintRole: "gate-site initialization",
    blueprintFamilies: "Wormgate Spine precursor; Arkseed Migration Fleet", civLane: "route-planner civilization",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, dark studio void background. A small aperture seed — ovoid, translucent blue-sapphire casing with a spatial seam visible as a thin luminous line running along its equator; the seam glows blue where the gate potential is stored. Handheld scale, fills the frame. Palette: deep sapphire blue, luminous spatial seam, near-black void. No planets, no full gate structure, no text." },

  t2s02: { name: "Storm-Memory Filament",         flavor: "This thread remembers every solar storm it has survived, then warns the worlds before the next one learns their names.",
    practicalUse: "Stores, indexes, or releases critical memory for Heliosphere Weather Loom infrastructure.",
    artifactForm: "Archive / Sensor", blueprintRole: "stellar weather memory",
    blueprintFamilies: "Heliosphere Weather Loom; Matrioshka Mind", civLane: "heliosphere archivist culture",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, soft atmospheric cool glow background — faint blue storm-light. A fine memory filament coiled loosely: the thread is deep sapphire with storm-pattern data encoded as subtle periodic color variations along its length, each band a stored storm event; the filament glows faintly blue. Fills the frame. Palette: deep sapphire blue, cool storm-light variations, blue atmospheric glow. No full solar array, no planets, no text." },

  t2s03: { name: "Simulation Loom",               flavor: "A loom that weaves possible years, then cuts the strands that demand too many graves.",
    practicalUse: "Manufactures or patterns specialized components needed by Matrioshka Mind projects.",
    artifactForm: "Fabrication Tool / Computation Substrate", blueprintRole: "predictive model weaving",
    blueprintFamilies: "Matrioshka Mind; Causality Audit Court precursor", civLane: "simulation guild civilization",
    engineeringScale: "Star-system",
    artPrompt: "Installation-scale eye-level view, dark studio void background. A simulation loom filling a warehouse: dark metal frame spans from floor to ceiling and wall to wall, with luminous sapphire-blue threads stretched across it in complex branching patterns; cut threads hang free (rejected timelines) while intact threads glow steadily across the full span. The loom fills the frame completely. Palette: deep blue simulation threads, dark metal frame, near-black void. No text." },

  t2s04: { name: "Continuity Vessel",             flavor: "A vessel that keeps a people continuous when distance tries to make them merely related.",
    practicalUse: "Holds hazardous forces in usable form for Arkseed Migration Fleet systems.",
    artifactForm: "Archive / Containment", blueprintRole: "identity continuity preservation",
    blueprintFamilies: "Arkseed Migration Fleet; Spiral-Arm Archive precursor", civLane: "migration memory civilization",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop eye-level view, dark studio void background. A sealed cylindrical archive vessel in dark blue-grey metal; a band of memory light glows along the mid-section, pale sapphire-white, indicating active identity continuity storage. No portraits, no people visible. Handheld scale, sits upright. Palette: dark blue-grey metal, pale sapphire memory band, near-black void. No people, no solar system imagery, no text." },

  t2s05: { name: "Mnemosyne Star-Index",          flavor: "An index that lets every world remember the same disaster without agreeing on the same myth.",
    practicalUse: "Stores, indexes, or releases critical memory for Matrioshka Mind infrastructure.",
    artifactForm: "Archive / Civic Signal Object", blueprintRole: "multi-world memory indexing",
    blueprintFamilies: "Matrioshka Mind; Spiral-Arm Archive precursor", civLane: "distributed archive civilization",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, soft atmospheric cool glow background. An index shard or prism — faceted deep blue, with faint star-map geometry hints visible as internal refraction patterns inside the crystal; the facets catch sapphire and pale gold light. Handheld scale, sits on a dark surface. Palette: deep sapphire blue, pale gold refraction hints, cool atmospheric glow. No words, no text anywhere in the image." },

  t2s06: { name: "Convergence Lens",              flavor: "A lens that shows when different categories are being forced to pretend they were always one.",
    practicalUse: "Reveals dangerous states early so Singularity Containment Mandala precursor systems can be corrected before failure.",
    artifactForm: "Sensor / Interface", blueprintRole: "wildcard pressure inspection",
    blueprintFamilies: "Singularity Containment Mandala precursor; Causality Audit Court precursor", civLane: "convergence-risk civilization",
    engineeringScale: "Star-system",
    artPrompt: "Planetary-scale eye-level view, planetary backdrop background — atmosphere and surface horizon visible. The convergence lens as a planet-spanning detection array: a massive white-gold lens structure visible at planetary scale, its surface catching multiple wavelengths of convergence pressure simultaneously; chromatic boundary edges bloom along the lens face where categories are being forced together. Palette: white-gold lens array, chromatic convergence edge light, planet horizon. No text." },

  // ── Tier 2 ─ Verdance ────────────────────────────────────────────────────
  t2e01: { name: "Solar Immune Organ",      flavor: "Grown inside orbital habitats, it teaches living tissue which starlight to welcome and which to refuse.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Heliosphere Weather Loom projects.",
    artifactForm: "Biotech Module / Defense", blueprintRole: "radiation adaptation",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "multi-world biosphere civilization",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, dark studio void background. A compact solar immune organ — a dense organic graft, deep green with internal immune-pattern architecture visible through its semi-translucent surface; radiation-filter layers are stacked inside like interference gratings. Fills the frame, palm-sized. Palette: deep green, semi-translucent immune layers, warm solar-edge glow at the surface. No whole worldroot, no planets, no text." },

  t2e02: { name: "Dormancy Clock Graft",    flavor: "A graft that lets a habitat sleep for centuries without forgetting when to wake hungry.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Arkseed Migration Fleet projects.",
    artifactForm: "Biotech Module / Archive", blueprintRole: "long-cycle dormancy timing",
    blueprintFamilies: "Arkseed Migration Fleet; Stellar Nursery Rite", civLane: "deep-time biological culture",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, mineral/rock surface background — dark aged bark or hull material. A biological clock-graft adhering to an organic surface: ring-pattern growth cycles are visible on the graft's upper surface like tree rings; the dormancy mechanism is a sealed bud at center, dark and compressed. Fills the frame, palm-sized. Palette: dark green-brown graft, ring pattern growth bands, dark bark substrate. No planets, no cosmic scene, no text." },

  t2e03: { name: "Abyssal Culture Flask",   flavor: "A sealed flask of life trained to grow where sunlight is a rumor and pressure is weather.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Heliopause Bastion projects.",
    artifactForm: "Biotech Module / Containment", blueprintRole: "dark-adapted culture growth",
    blueprintFamilies: "Heliopause Bastion; Spiral Ecology Mesh precursor", civLane: "dark-adapted biosphere culture",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop eye-level view, dark studio void background. A sealed dark culture flask — pressure-rated, dark metal and tinted glass casing; inside, bioluminescent dark-adapted organisms glow faint blue-green in their growth medium; the flask is compact, pressure-sealed for deep dark environments. Handheld scale. Palette: near-black flask body, faint blue-green bioluminescence inside, dark void. No full garden, no planets, no text." },

  t2e04: { name: "Mycelial Relay Spindle",  flavor: "A spindle of engineered mycelium that translates between habitat, ship, soil, and silence.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Arkseed Migration Fleet projects.",
    artifactForm: "Interface / Biotech Module", blueprintRole: "interplanetary biological signaling",
    blueprintFamilies: "Arkseed Migration Fleet; Heliosphere Weather Loom", civLane: "symbiotic signal civilization",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, dark studio void background. A mycelial relay spindle — a finger-length biological spool with engineered mycelium threads wound around it; the threads are deep green with bioluminescent signal nodes at regular intervals along their length. The spindle sits upright on a dark surface. Palette: deep green mycelium, pale bioluminescent nodes, dark void. No huge network, no planets, no text." },

  t2e05: { name: "Epoch Graft Ledger",      flavor: "A living ledger that changes tissue when an age ends, so the body learns history before the mind does.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Arkseed Migration Fleet projects.",
    artifactForm: "Archive / Biotech Module", blueprintRole: "biological era-tracking",
    blueprintFamilies: "Arkseed Migration Fleet; Spiral-Arm Archive precursor", civLane: "living chronology civilization",
    engineeringScale: "Star-system",
    artPrompt: "Installation-scale eye-level view, soft atmospheric green glow background. A living epoch-ledger covering an entire wall face: growth-ring strata in living tissue stripe the surface from floor to ceiling in horizontal bands, each layer a distinct era of biological history; the newest layer glows faint green at the top. The ledger wall fills the frame. Palette: deep green strata bands, pale living surface glow, atmospheric green light. No readable text, no planets." },

  t2e06: { name: "Crystal Biome Seedplate", flavor: "A seedplate that grows transparent habitats where crystal structure and living metabolism negotiate.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Heliosphere Weather Loom projects.",
    artifactForm: "Material / Biotech Module", blueprintRole: "crystal-organic habitat seeding",
    blueprintFamilies: "Heliosphere Weather Loom; Stellar Nursery Rite", civLane: "crystalline ecology civilization",
    engineeringScale: "Star-system",
    artPrompt: "Installation-scale cross-section view, mineral/rock surface background — crystal formation substrate. A seedplate in cross-section at architectural scale: the cut reveals alternating crystal and living-cell layers spanning meters of depth; the crystal planes are translucent green-white, the organic layers between them pale and metabolically active. The cross-section face fills the frame entirely. Palette: translucent green-white crystal, pale organic cell layers, mineral substrate. No full biome, no text." },

  // ── Tier 2 ─ Abyss ───────────────────────────────────────────────────────
  t2o01: { name: "Horizon Extractor",         flavor: "An extractor that samples the edge of forbidden physics without inviting the edge inside.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Dark-Sector Observatory systems.",
    artifactForm: "Sensor / Containment", blueprintRole: "boundary-energy sampling",
    blueprintFamilies: "Dark-Sector Observatory; Starlift Foundry", civLane: "horizon engineer civilization",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop eye-level view, abstract energy field background — dark with a sharp boundary edge where physics changes. A compact extractor tool positioned at an abstract horizon boundary — dark metal housing with a sample probe extended toward the edge; the probe tip glows pale blue-white where it touches forbidden-physics space. Handheld device scale. Palette: dark metal, pale blue-white probe tip, dark energy boundary. No full black hole scene, no planets, no text." },

  t2o02: { name: "Radiant Erasure Casket",    flavor: "A casket for dangerous light, sealing revelations until public knowledge can survive them.",
    practicalUse: "Coordinates public trust, law, or multi-party agreement for Heliopause Bastion systems.",
    artifactForm: "Containment / Protocol", blueprintRole: "authorized signal deletion",
    blueprintFamilies: "Heliopause Bastion; Worldshield Covenant", civLane: "lawful redaction civilization",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, dark studio void background. A small dark casket — near-black metal with a sealed lid; white-gold light bleeds from the seam around the lid, the contained revelation pressing against its bounds but unable to escape. Matchbox-sized scale, fills the frame. Palette: near-black casket, white-gold light seam, deep void. No text, no labels." },

  t2o03: { name: "Entropic Furnace Baffle",   flavor: "A baffle that routes stellar waste into shadowed work instead of letting heat become confession.",
    practicalUse: "Functions as a specialized thermal control / defense for Starlift Foundry projects.",
    artifactForm: "Thermal Control / Defense", blueprintRole: "entropy redirection",
    blueprintFamilies: "Starlift Foundry; Matrioshka Mind", civLane: "waste-heat shadow culture",
    engineeringScale: "Star-system",
    artPrompt: "Room-scale eye-level view, soft atmospheric dark glow background — deep shadow environment. A large dark thermal baffle — wall-mounted, dark absorptive panels with recessed routing channels that direct waste heat into hidden work chambers; faint deep-orange glow visible in the channel voids. The baffle fills the frame. Palette: near-black absorptive panels, deep orange heat in channels, dark shadow atmosphere. No giant furnace, no planets, no text." },

  t2o04: { name: "Extinction Forge Die",      flavor: "A die cast from failed worlds, used to make replacement parts for futures that nearly ended.",
    practicalUse: "Manufactures or patterns specialized components needed by Galactic Relic Forge precursor projects.",
    artifactForm: "Fabrication Tool / Archive", blueprintRole: "post-collapse reconstruction tooling",
    blueprintFamilies: "Galactic Relic Forge precursor; Spiral-Arm Archive precursor", civLane: "extinction-survivor culture",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, mineral/rock surface background — dark ash and fossilized debris. A small forge die — cube-shaped, cast from dark composite material containing visible fossil and ash inclusions from failed worlds; the die faces bear geometric replacement-part cavity profiles. Fingertip-sized. Palette: dark composite with ash-grey and fossil inclusions, near-black surfaces. No text, no labels on the die faces." },

  t2o05: { name: "Eventide Ecology Seal",     flavor: "A seal that lets an ecosystem go dark gracefully instead of collapsing into hunger.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Heliosphere Weather Loom projects.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "managed ecological shutdown",
    blueprintFamilies: "Heliosphere Weather Loom; Spiral Ecology Mesh precursor", civLane: "twilight ecology civilization",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, soft atmospheric twilight glow background — dim green fading to dark. A dim ecology seal token — organic material, deep green on its outer rim grading to near-black at center; a living ecological pattern is visible as a faint relief on its surface, in the process of gracefully dimming. Coin-sized scale. Palette: deep green outer rim, twilight fade to near-black center, dim atmospheric glow. No text on token surface." },

  t2o06: { name: "Dimensional Shear Gauge",   flavor: "A gauge that measures when space is about to stop being infrastructure and start being injury.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Heliopause Bastion operations.",
    artifactForm: "Sensor / Interface", blueprintRole: "boundary stress measurement",
    blueprintFamilies: "Heliopause Bastion; Wormgate Spine precursor", civLane: "spatial stress engineer civilization",
    engineeringScale: "Star-system",
    artPrompt: "Planetary-scale cross-section view, planetary backdrop background — surface and atmosphere visible. A dimensional shear gauge array spanning a hemisphere in cross-section: the shear boundary slices through the planet's upper atmosphere as a visible tear; the gauge chambers are planetary-scale structures embedded in the crust, their stress-indicator filaments bent by the shear force and visible against the atmospheric limb. Palette: dark metal gauge structures, pale shear-distortion lines across atmosphere, planet surface texture. No warship, no text." },

  // ── Tier 2 ─ Radiance ────────────────────────────────────────────────────
  t2p01: { name: "Containment Lattice",       flavor: "A containment lattice built to be inspected by citizens, not merely trusted by engineers.",
    practicalUse: "Holds hazardous forces in usable form for Starlift Foundry systems.",
    artifactForm: "Containment / Civic Signal", blueprintRole: "public-safe hazardous containment",
    blueprintFamilies: "Starlift Foundry; Singularity Containment Mandala precursor", civLane: "transparent containment civilization",
    engineeringScale: "Star-system",
    artPrompt: "Installation-scale eye-level view, dark studio void background. A multi-story containment lattice facade — white-gold geometric frame with transparent hazard-containment cells arranged in a regular grid across the entire building face; each cell glows softly from within, designed so citizens at ground level can inspect each chamber. The lattice fills the frame from edge to edge. Palette: white-gold frame, luminous containment cell glow, near-black void. No text." },

  t2p02: { name: "Null-Convergence Prism",    flavor: "A prism that brightens when too many meanings are being crushed into one convenient answer.",
    practicalUse: "Reveals dangerous states early so Singularity Containment Mandala precursor systems can be corrected before failure.",
    artifactForm: "Sensor / Interface", blueprintRole: "category collapse warning",
    blueprintFamilies: "Singularity Containment Mandala precursor; Matrioshka Mind", civLane: "convergence-auditing civilization",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop eye-level view, abstract energy field background — white convergence pressure waves. A prism with chromatic warning edges: normally neutral, when category convergence is detected the prism face blazes with separated white chromatic boundaries; the edges catch light sharply as distinct spectra. Handheld scale. Palette: white chromatic edges, pale lens body, abstract energy field. No planets, no text." },

  t2p03: { name: "Living Treaty Organ",       flavor: "An organ grown to hold agreements between worlds whose bodies disagree about what comfort means.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Heliosphere Weather Loom projects.",
    artifactForm: "Biotech Module / Civic Protocol", blueprintRole: "multi-world biological governance",
    blueprintFamilies: "Heliosphere Weather Loom; Galactic Concordance Engine precursor", civLane: "plural civic ecology",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, dark studio void background. A living treaty organ — an organic structure with geometric gold signal lines running through its tissue in a regular treaty-geometry pattern; the gold lines glow where inter-world agreements are actively maintained. Palm-sized, fills the frame. Palette: living cream-green tissue, geometric gold signal lines, dark void. No text, no portraits." },

  t2p04: { name: "Heliostat Filament",        flavor: "A single filament from a light-steering civilization; in the right orbit, it can teach mirrors to cooperate.",
    practicalUse: "Functions as a specialized power component / signal object for Dyson Swarm projects.",
    artifactForm: "Power Component / Signal Object", blueprintRole: "stellar light alignment",
    blueprintFamilies: "Dyson Swarm; Heliosphere Weather Loom", civLane: "solar coordination civilization",
    engineeringScale: "Star-system",
    artPrompt: "Extreme macro close-up, soft atmospheric gold glow background. A single fine gold-white heliostat filament — an almost impossibly thin thread that catches and refracts light along its entire length; micro-etched orbital guidance marks are visible as subtle texture. Fills the frame. Palette: warm gold-white filament, luminous gold atmospheric glow. No full solar array, no planets, no text." },

  t2p05: { name: "Error-Correcting Core",     flavor: "A core that spends more energy admitting mistakes than lesser machines spend pretending not to make them.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Matrioshka Mind systems.",
    artifactForm: "Computation Substrate / Protocol", blueprintRole: "high-energy error correction",
    blueprintFamilies: "Matrioshka Mind; Causality Audit Court precursor", civLane: "precision computation civilization",
    engineeringScale: "Star-system",
    artPrompt: "Installation-scale product-shot, 3/4 overhead angle, dark studio void background. A large-scale error-correcting computation facility: a building-height cylindrical structure in white-gold housing, its exterior surface covered in ordered correction-geometry panels that glow warm white; concentric correction-field architecture is visible as raised relief banding around the full circumference. The structure fills the frame. Palette: white-gold housing, ordered geometric correction glow, dark void. No text, no labels." },

  t2p06: { name: "Radiation Treaty Prism",    flavor: "A prism used to negotiate how much stellar danger each habitat agrees to bear for the others.",
    practicalUse: "Reveals dangerous states early so Heliosphere Weather Loom systems can be corrected before failure.",
    artifactForm: "Civic Signal / Sensor", blueprintRole: "shared radiation governance",
    blueprintFamilies: "Heliosphere Weather Loom; Arkseed Migration Fleet", civLane: "multi-world biosphere treaty culture",
    engineeringScale: "Star-system",
    artPrompt: "Tabletop eye-level view, nebula field background — distant stellar cloud, no planets or moons. A radiation treaty prism in white-gold housing: its faces are tuned to specific habitat-tolerance wavelengths, each face catching a different treaty-band of stellar light. The nebula behind provides soft stellar context without dominating. Handheld scale. Palette: white-gold prism, multi-band stellar light refraction, soft nebula field. No text, no labels." },
};

// Tier 3 ── added separately so the file stays scannable
Object.assign(CARD_LORE, {
  // ── Tier 3 ─ Flare ─────────────────────────────────────────────────────
  t3r01: { name: "Relic Ignition Key",           flavor: "A key that starts machines no single star system could afford to misunderstand.",
    practicalUse: "Functions as a specialized power component / interface for Galactic Relic Forge projects.",
    artifactForm: "Power Component / Interface", blueprintRole: "relic-scale activation",
    blueprintFamilies: "Galactic Relic Forge; Star-River Migration Lattice", civLane: "relic-making expansion civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop eye-level view, nebula field background — faint stellar cloud, no planets or moons. A hand-sized ignition key in relic metal — aged dark alloy with red-gold plasma channeled along its key-bit geometry; the activation contacts glow with contained ignition potential. Sits on an implied surface. Palette: aged dark alloy, red-gold plasma channels, soft nebula behind. No galaxy disc, no text." } as CardLore,

  t3r02: { name: "Extinction Furnace Veto",      flavor: "A veto token used when a civilization proves it can build an extinction furnace and chooses not to open it.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Causality Audit Court systems.",
    artifactForm: "Protocol / Control Instrument", blueprintRole: "civilization-ending energy veto",
    blueprintFamilies: "Causality Audit Court; Black-Map Pilgrimage Engine", civLane: "catastrophe-governance culture",
    engineeringScale: "Galactic",
    artPrompt: "Extreme macro close-up, dark studio void background. A small flat veto seal in dark metal: its face is smooth except for a single authorized extinction-refusal mark pressed into the center; the only visual reference to the furnace is a faint reflection of red-orange heat visible on the polished underside. Coin-sized scale, fills the frame. Palette: near-black metal seal, faint red-orange reflection, dark void. No giant furnace, no planets, no text on the face." } as CardLore,

  t3r03: { name: "Temporal Burn Audit Lens",     flavor: "A lens that traces which histories were burned as fuel before the winning timeline called itself natural.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Causality Audit Court systems.",
    artifactForm: "Sensor / Protocol", blueprintRole: "timeline-energy risk audit",
    blueprintFamilies: "Causality Audit Court; Spiral-Arm Archive", civLane: "temporal hazard civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, soft atmospheric warm-cool glow background — amber-to-blue gradient. A compact audit lens in a dark housing: when held to the light, controlled fire-time traces are visible within the glass as faint orange-red filaments crossing sapphire temporal thread lines, revealing burned histories. Handheld scale. Palette: warm orange history traces, cool sapphire temporal lines, dark housing. No giant event, no planets, no text." } as CardLore,

  t3r04: { name: "Star-River Propulsion Core",   flavor: "A propulsion core calibrated for living habitats, powerful enough to move homes without turning them into cargo.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Star-River Migration Lattice projects.",
    artifactForm: "Power Component / Biotech Interface", blueprintRole: "biosphere migration propulsion",
    blueprintFamilies: "Star-River Migration Lattice; Galactic Relic Forge", civLane: "living expansion civilization",
    engineeringScale: "Galactic",
    artPrompt: "Stellar-scale eye-level view, stellar backdrop background — star visible as luminous context, no planets. The star-river propulsion core as a stellar installation: a massive cylindrical structure in stellar orbit, dark metal with biological interface ports scaled to accept entire living habitats; red-gold propulsion energy streams from the drive end and green bio-coupling glow illuminates the habitat interface zone. Palette: dark metal, red-gold propulsion energy, green biological interface glow, stellar light. No text, no labels." } as CardLore,

  // ── Tier 3 ─ Continuum ─────────────────────────────────────────────────
  t3s01: { name: "Voidline Compass",             flavor: "It fits in one hand, but only a civilization with a galaxy of mistakes can read where it points.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Wormgate Spine operations.",
    artifactForm: "Transit Component / Sensor", blueprintRole: "hidden route detection",
    blueprintFamilies: "Wormgate Spine; Dark-Sector Observatory", civLane: "lawful hidden-transit civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop eye-level view, dark studio void background. A palm-sized compass instrument — dark metal housing, its needle is a sliver of voidline material that points along hidden transit routes; subtle star-route hints are etched on the compass rose as geometric paths. Sits upright. Palette: dark metal, voidline needle with cool blue-black glow, dark void. No giant structure, no planets, no text." } as CardLore,

  t3s02: { name: "Recursion Witness Key",        flavor: "A key held by the witness, not the engineer, because recursion without testimony becomes tyranny.",
    practicalUse: "Governs dangerous decisions or sequences so Causality Audit Court systems can operate safely.",
    artifactForm: "Protocol / Civic Signal", blueprintRole: "dangerous recursion authorization",
    blueprintFamilies: "Causality Audit Court; Spiral-Arm Archive", civLane: "legal-temporal civilization",
    engineeringScale: "Galactic",
    artPrompt: "Extreme macro close-up, dark studio void background. A slim authorization key with recursive geometry — the key bit is a self-similar fractal pattern cut from deep sapphire metal; the shaft is smooth dark material. Finger-length scale, fills the frame. Palette: deep sapphire-blue recursive bit geometry, dark metal shaft, near-black void. No giant fire, no planets, no text." } as CardLore,

  t3s03: { name: "Ancestor Signal Key",          flavor: "It unlocks messages sent by species that died before your star was named.",
    practicalUse: "Functions as a specialized archive / civic signal for Spiral-Arm Archive projects.",
    artifactForm: "Archive / Civic Signal", blueprintRole: "extinct-civilization handshake",
    blueprintFamilies: "Spiral-Arm Archive; Galactic Concordance Engine", civLane: "archivist civilization",
    engineeringScale: "Galactic",
    artPrompt: "Extreme macro close-up, soft atmospheric cool-gold glow background — ancient starlight quality. A signal key or shard with fossil star-language motifs: the key surface is covered in eroded geometric message-geometry from an extinct civilization, glowing faintly sapphire-gold where the signal is still active. Finger-length scale, fills the frame. Palette: aged metal with fossil sapphire-gold motifs, faint cool-gold atmospheric glow. No readable text, no letters." } as CardLore,

  t3s04: { name: "Chronology Governor",          flavor: "A governor for calendars that span species, relativistic routes, and wars over who gets to define before.",
    practicalUse: "Functions as a specialized control instrument / protocol for Causality Audit Court projects.",
    artifactForm: "Control Instrument / Protocol", blueprintRole: "galactic timeline governance",
    blueprintFamilies: "Causality Audit Court; Spiral-Arm Archive", civLane: "chronology-governing civilization",
    engineeringScale: "Galactic",
    artPrompt: "Stellar-scale eye-level view, stellar backdrop background — star and stellar cloud visible as context. The chronology governor as a stellar authority station: a large precision governance structure in stellar orbit, dark sapphire-blue metal with time-map facets catching stellar light; calibration mechanisms visible along its equatorial band; the station maintains galactic calendar agreement from its stellar vantage. Palette: deep sapphire-blue metal, dark time-map facets, stellar light. No crown, no text." } as CardLore,

  // ── Tier 3 ─ Verdance ──────────────────────────────────────────────────
  t3e01: { name: "Cryptobiotic Root Key",        flavor: "A root key that wakes only on worlds where the old biosphere left permission buried in the soil.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Spiral Ecology Mesh projects.",
    artifactForm: "Biotech Module / Transit Component", blueprintRole: "dormant biosphere routing",
    blueprintFamilies: "Spiral Ecology Mesh; Wormgate Spine", civLane: "hidden ancestral biosphere civilization",
    engineeringScale: "Galactic",
    artPrompt: "Extreme macro close-up, mineral/rock surface background — dark ancient soil, fossil root debris. A small root key in dormant state — organic-composite material, its key-tip is a biological probe with dormant organic patterns pressed into its surface; no light, no growth yet. Finger-length scale, fills the frame. Palette: dark green-brown organic composite, fossil root texture, dark soil background. No giant roots, no planets, no text." } as CardLore,

  t3e02: { name: "Ecology Substrate Code",       flavor: "A substrate code that lets unrelated biospheres share corridors without becoming one invasive species.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Spiral Ecology Mesh projects.",
    artifactForm: "Protocol / Biotech Module", blueprintRole: "galactic ecology compatibility",
    blueprintFamilies: "Spiral Ecology Mesh; Galactic Concordance Engine", civLane: "distributed ecology civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop eye-level view, dark studio void background. A protocol substrate object — flat organic seed-plate with ecology compatibility code pressed into its surface as geometric biological patterns: cellular geometries, root-network junctions, symbiosis-boundary markers — all in relief, no letters. Handheld tile scale. Palette: deep green-brown organic, pale substrate geometry, dark void. No text, no letter characters anywhere in the image." } as CardLore,

  t3e03: { name: "Ancestral Immune Code",        flavor: "An immune code written by extinct ecologies to protect living worlds from repeating their last appetite.",
    practicalUse: "Stores, indexes, or releases critical memory for Spiral Ecology Mesh infrastructure.",
    artifactForm: "Biotech Module / Archive", blueprintRole: "dead-lineage immune memory",
    blueprintFamilies: "Spiral Ecology Mesh; Spiral-Arm Archive", civLane: "ancestral necrobiome civilization",
    engineeringScale: "Galactic",
    artPrompt: "Galactic-scale eye-level view, galactic backdrop background — deep space, galactic-arm star field and nebula cloud visible. The ancestral immune code as a biological formation spanning a galactic arm: vast organic immune-pattern structures formed by extinct ecologies, dark green with pale geometric lattice visible at cosmic scale; the formation extends to the edges of the frame. Palette: deep green biological mass, pale immune-geometry edges, distant star-field and nebula. No text, no labels." } as CardLore,

  t3e04: { name: "Plurality Charter Seed",       flavor: "A charter seed that grows different laws for different bodies without letting one species become the soil.",
    practicalUse: "Provides engineered biological adaptation, repair, or growth for Galactic Concordance Engine projects.",
    artifactForm: "Protocol / Biotech Module / Civic Signal", blueprintRole: "multi-species coexistence seed",
    blueprintFamilies: "Galactic Concordance Engine; Spiral Ecology Mesh", civLane: "plural civic ecology civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, soft atmospheric gold-green glow background. A compact seed/seal hybrid — ovoid organic casing covered in many different biological geometries pressed into its surface, each representing a different species' charter in relief; the casing glows faintly gold-green where active charter growth is occurring. Handheld scale. Palette: organic green-gold, multi-geometry relief, warm glow. No crown, no planets, no text." } as CardLore,

  // ── Tier 3 ─ Abyss ─────────────────────────────────────────────────────
  t3o01: { name: "Buried Biosphere Seal",        flavor: "A seal that keeps a biosphere dormant through centuries of discovery by civilizations too loud to trust.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Spiral Ecology Mesh operations.",
    artifactForm: "Defense / Biotech Module", blueprintRole: "hidden biosphere preservation",
    blueprintFamilies: "Spiral Ecology Mesh; Dark-Sector Observatory", civLane: "buried survival civilization",
    engineeringScale: "Galactic",
    artPrompt: "Extreme macro close-up, mineral/rock surface background — compressed dark soil, ancient root debris. A small buried seal — near-black disc, its face covered in dark organic root hints visible only under oblique light; the seal is deliberately inconspicuous. Coin-sized scale, fills the frame. Palette: near-black seal, dark green root micro-texture, compressed soil substrate. No full planet, no text." } as CardLore,

  t3o02: { name: "Collapse Audit Mirror",        flavor: "A mirror that does not show ruin; it shows which safeguards were missing before anyone called ruin inevitable.",
    practicalUse: "Reveals dangerous states early so Causality Audit Court systems can be corrected before failure.",
    artifactForm: "Sensor / Protocol", blueprintRole: "collapse-risk reflection",
    blueprintFamilies: "Causality Audit Court; Singularity Containment Mandala", civLane: "collapse-auditing civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop eye-level view, dark studio void background. A dark audit mirror in a precision frame — the reflective face shows not the viewer's face but a fractured ecological reflection: incomplete safeguard geometries visible as refracted ghost images within the mirror surface, showing what was missing. Handheld scale. Palette: near-black mirror, dark fractured ecological reflection, deep void. No ruin imagery, no planets, no text." } as CardLore,

  t3o03: { name: "Silence Archive Shard",        flavor: "A shard that stores signals by hiding them so well that only the intended future can find them.",
    practicalUse: "Detects, hides, or stabilizes hazardous hidden conditions for Dark-Sector Observatory operations.",
    artifactForm: "Archive / Concealment", blueprintRole: "hidden signal preservation",
    blueprintFamilies: "Dark-Sector Observatory; Spiral-Arm Archive", civLane: "silent observer civilization",
    engineeringScale: "Galactic",
    artPrompt: "Extreme macro close-up, dark studio void background. A black archive shard — deep void-black material, smooth surfaces; faint sealed signal lines are just visible as hairline luminous traces on two faces, the only indication that information is stored inside. Fills the frame, finger-length scale. Palette: near-black shard, hairline signal traces in pale blue-white, deep void. No text, no labels." } as CardLore,

  t3o04: { name: "Dark-Sector Aperture",         flavor: "An aperture into regions that maps cannot admit exist until a civilization is ready to be watched back.",
    practicalUse: "Reveals dangerous states early so Dark-Sector Observatory systems can be corrected before failure.",
    artifactForm: "Interface / Sensor", blueprintRole: "forbidden-sector observation",
    blueprintFamilies: "Dark-Sector Observatory; Black-Map Pilgrimage Engine", civLane: "hidden observer civilization",
    engineeringScale: "Galactic",
    artPrompt: "Galactic-scale eye-level view, galactic backdrop background — deep cosmic void, no galaxy disc at center. The dark-sector aperture as a galactic sensor array: an enormous black aperture structure spanning a galactic sector, the opening reveals void-distortion and forbidden-physics shimmer at cosmic scale; the aperture edges are dark refractory material with pale observation-boundary glow. Palette: near-black aperture structure, void-distortion interior, pale forbidden-physics edge glow. No text, no labels." } as CardLore,

  // ── Tier 3 ─ Radiance ──────────────────────────────────────────────────
  t3p01: { name: "Concordance Seal",             flavor: "No empire can counterfeit it; the seal only opens when rival species agree on what must not be owned.",
    practicalUse: "Coordinates public trust, law, or multi-party agreement for Galactic Concordance Engine systems.",
    artifactForm: "Protocol / Civic Signal Object", blueprintRole: "multi-species legitimacy",
    blueprintFamilies: "Galactic Concordance Engine; Causality Audit Court", civLane: "plural civic civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop eye-level view, dark studio void background. A flat white-gold civic seal — its face carries void accents as dark inlaid geometry between the gold concordance pattern; the seal radiates quiet authority. Handheld scale, sits on dark surface. Palette: white-gold, void-dark inlay geometry, near-black void background. No giant lattice, no planets, no text." } as CardLore,

  t3p02: { name: "Public Maker-Seal",            flavor: "A maker-seal proving that an impossible artifact was built under law, not merely under power.",
    practicalUse: "Manufactures or patterns specialized components needed by Galactic Relic Forge projects.",
    artifactForm: "Civic Signal / Fabrication Protocol", blueprintRole: "authorized relic manufacture",
    blueprintFamilies: "Galactic Relic Forge; Matrioshka Mind", civLane: "relic-making civic civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, mineral/rock surface background — dark polished stone. A compact official maker-seal in white-gold: its face bears a computronium microtexture — fine interlocking computation-substrate patterns pressed into the metal at near-atomic scale, visible as a shimmering geometric relief. Coin-sized. Palette: white-gold, computronium microtexture shimmer, dark polished stone. No text, no labels." } as CardLore,

  t3p03: { name: "Thermal Logic Wafer",          flavor: "A wafer of logic designed around waste heat, because even thought must answer for what it burns.",
    practicalUse: "Provides controlled energy, heat, or ignition support for Matrioshka Mind systems.",
    artifactForm: "Computation Substrate / Thermal Control", blueprintRole: "star-powered computation unit",
    blueprintFamilies: "Matrioshka Mind; Galactic Relic Forge", civLane: "nested computational archive civilization",
    engineeringScale: "Galactic",
    artPrompt: "Stellar-scale eye-level view, stellar backdrop background — star visible as luminous context in the distance, no planets. The thermal logic wafer manifested at computation-moon scale: a vast flat luminous structure in stellar orbit, white-gold with nested thermal computation channels visible as warm orange traces across its face; the scale is comparable to a moon, visible against the star behind it. Palette: white-gold surface, warm orange thermal computation traces, stellar light. No text, no labels." } as CardLore,

  t3p04: { name: "Species-Rights Witness Prism", flavor: "A witness prism that records not who rules, but which kinds of beings were allowed to remain themselves.",
    practicalUse: "Reveals dangerous states early so Galactic Concordance Engine systems can be corrected before failure.",
    artifactForm: "Civic Signal / Sensor", blueprintRole: "multi-species rights verification",
    blueprintFamilies: "Galactic Concordance Engine; Spiral-Arm Archive", civLane: "multi-species civic civilization",
    engineeringScale: "Galactic",
    artPrompt: "Tabletop product-shot, 3/4 overhead angle, soft atmospheric multi-tone glow background — warm white-gold with faint varied species-light hues. A witness prism that refracts multi-species life signatures: when held up, each species' rights-light exits as a distinct wavelength from a different face; the prism body is white-gold with multiple life-hue refractions active simultaneously. Handheld scale. Palette: white-gold prism, multiple subtle life-hue refractions, warm atmospheric glow. No crown, no ruler figure, no text." } as CardLore,
});

export function getCardLore(id: string): CardLore {
  return CARD_LORE[id] ?? { name: "Unnamed Artifact", flavor: "" };
}
