// Generated once from the pre-v2 server catalogs. technology.ts applies the
// canonical v2 metadata and is the public source of truth.
export const ARTIFACT_BASE_DEFINITIONS = {
  "t1r01": {
    "id": "t1r01",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 1,
      "abyss": 1,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Ignition Kernel",
    "flavor": "A caged spark that lights furnaces and cities but refuses to spread. No one knows who first taught fire restraint.",
    "artifactForm": "Power Component / Control Instrument",
    "blueprintRole": "controlled ignition and thermal regulation",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Planetary Cradle Engine",
    "civLane": "planetary forge culture",
    "engineeringScale": "Planetary"
  },
  "t1r02": {
    "id": "t1r02",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 1,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Ashroot Bloom",
    "flavor": "Pale shoots rise from soil too burned for life. They always bend toward something still moving beneath the ash.",
    "artifactForm": "Biotech Module / Catalyst",
    "blueprintRole": "post-burn ecological recovery",
    "blueprintFamilies": "Planetary Cradle Engine; Stellar Nursery Rite precursor",
    "civLane": "phoenix biosphere",
    "engineeringScale": "Planetary"
  },
  "t1r03": {
    "id": "t1r03",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 1,
      "verdance": 1,
      "abyss": 0,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Chrono-Ember Core",
    "flavor": "It remembers when a fire must return, not how it burned. Some cores wake long after their makers are gone.",
    "artifactForm": "Archive / Power Component",
    "blueprintRole": "energy-memory synchronization",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Spiral-Arm Archive precursor",
    "civLane": "deep-time ignition culture",
    "engineeringScale": "Planetary"
  },
  "t1r04": {
    "id": "t1r04",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 0,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Causal Spark Coil",
    "flavor": "Before it fires, the coil tests what the spark will cause. Sometimes it refuses without explaining why.",
    "artifactForm": "Control Instrument / Protocol Object",
    "blueprintRole": "safe trigger sequencing",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Causality Audit Court precursor",
    "civLane": "experimental causal engineer civilization",
    "engineeringScale": "Planetary"
  },
  "t1r05": {
    "id": "t1r05",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 2,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Voidflare Cask",
    "flavor": "A sealed burst of light kept for the moment every other flame fails. The cask grows warmer during eclipses.",
    "artifactForm": "Containment / Power Component",
    "blueprintRole": "volatile void-pressure ignition",
    "blueprintFamilies": "Worldshield Covenant; Mantle-to-Orbit Foundry",
    "civLane": "eclipse host civilization",
    "engineeringScale": "Planetary"
  },
  "t1r06": {
    "id": "t1r06",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 1,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Photosynthetic Wick",
    "flavor": "This living wick stores sunlight and releases it as gentle heat. Far from any star, it still leans toward dawn.",
    "artifactForm": "Biotech Module / Power Component",
    "blueprintRole": "biological energy conversion",
    "blueprintFamilies": "Planetary Cradle Engine; Ecumenopolis Lattice",
    "civLane": "solar-adapted biosphere civilization",
    "engineeringScale": "Planetary"
  },
  "t1r07": {
    "id": "t1r07",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 2,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Entropy Pyre Baffle",
    "flavor": "It channels dangerous waste heat into useful work. The soot patterns sometimes resemble maps of places that have not burned yet.",
    "artifactForm": "Containment / Thermal Control",
    "blueprintRole": "waste heat and decay routing",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Worldshield Covenant",
    "civLane": "entropy-tolerant industrial culture",
    "engineeringScale": "Planetary"
  },
  "t1r08": {
    "id": "t1r08",
    "tier": 1,
    "bonusAffinity": "flare",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 4,
      "singularity": 0
    },
    "name": "Oathfire Igniter",
    "flavor": "The igniter opens only before witnesses, turning flame into a public promise. Unrecorded fires will not answer it.",
    "artifactForm": "Civic Signal Object / Power Component",
    "blueprintRole": "public sanctioned ignition",
    "blueprintFamilies": "Ascension Registry; Galactic Concordance precursor",
    "civLane": "solar civic forge culture",
    "engineeringScale": "Planetary"
  },
  "t1s01": {
    "id": "t1s01",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 1,
      "abyss": 0,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Echo Splinter",
    "flavor": "A crystal splinter that hears a structure fail moments before it breaks. Each warning sounds faintly like a voice.",
    "artifactForm": "Archive / Sensor",
    "blueprintRole": "event echo capture",
    "blueprintFamilies": "Spiral-Arm Archive precursor; Worldshield Covenant",
    "civLane": "planetary memory culture",
    "engineeringScale": "Planetary"
  },
  "t1s02": {
    "id": "t1s02",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 1,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Mantlelift Driver Coil",
    "flavor": "This timed coil hurls sealed cargo from deep underground into orbit. A capsule that misses the rhythm is never found.",
    "artifactForm": "Transit Component / Power Component",
    "blueprintRole": "planetary-to-orbit mass acceleration",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Arkseed Migration Fleet precursor",
    "civLane": "orbital logistics civilization",
    "engineeringScale": "Planetary"
  },
  "t1s03": {
    "id": "t1s03",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 0,
      "abyss": 1,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Null-Loop Anchor",
    "flavor": "It stops machines trapped in endless repetition. Afterward, the anchor keeps counting cycles that never happened.",
    "artifactForm": "Control Instrument / Stabilization",
    "blueprintRole": "recursion boundary control",
    "blueprintFamilies": "Ascension Registry; Causality Audit Court precursor",
    "civLane": "recursion-safety civilization",
    "engineeringScale": "Planetary"
  },
  "t1s04": {
    "id": "t1s04",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Time-Crystal Scaffold",
    "flavor": "A crystal frame that makes distant machines share the same second. Watches placed near it begin agreeing too well.",
    "artifactForm": "Material / Fabrication Tool",
    "blueprintRole": "precision timing substrate",
    "blueprintFamilies": "Ecumenopolis Lattice; Matrioshka Mind precursor",
    "civLane": "timekeeping material culture",
    "engineeringScale": "Planetary"
  },
  "t1s05": {
    "id": "t1s05",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 2,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Silent Recursion Rule",
    "flavor": "A safety rule designed to work only while unspoken. Reading it aloud changes the final line.",
    "artifactForm": "Protocol / Archive",
    "blueprintRole": "quiet error correction",
    "blueprintFamilies": "Matrioshka Mind precursor; Worldshield Covenant",
    "civLane": "quiet planner civilization",
    "engineeringScale": "Planetary"
  },
  "t1s06": {
    "id": "t1s06",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 2,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Living Chronicle",
    "flavor": "This living record grows new pages as its people change. The oldest margins contain handwriting no one remembers adding.",
    "artifactForm": "Archive / Biotech Module",
    "blueprintRole": "adaptive civic memory",
    "blueprintFamilies": "Planetary Cradle Engine; Ecumenopolis Lattice",
    "civLane": "biological archive civilization",
    "engineeringScale": "Planetary"
  },
  "t1s07": {
    "id": "t1s07",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 0,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 0,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "String-Scar Loom",
    "flavor": "The loom turns flaws in impossible threads into exact building instructions. Its finest pattern came from a thread that broke itself.",
    "artifactForm": "Fabrication Tool / Material",
    "blueprintRole": "defect-pattern weaving",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Galactic Relic Forge precursor",
    "civLane": "defect-engineer culture",
    "engineeringScale": "Planetary"
  },
  "t1s08": {
    "id": "t1s08",
    "tier": 1,
    "bonusAffinity": "continuum",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 4,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Root Memory Valve",
    "flavor": "A valve releases ancestral memories in survivable doses. What it keeps buried presses back against the roots.",
    "artifactForm": "Archive / Biotech Module / Control Instrument",
    "blueprintRole": "selective memory release",
    "blueprintFamilies": "Planetary Cradle Engine; Spiral Ecology Mesh precursor",
    "civLane": "ancestral biosphere civilization",
    "engineeringScale": "Planetary"
  },
  "t1e01": {
    "id": "t1e01",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 1,
      "verdance": 0,
      "abyss": 0,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Replication Spore",
    "flavor": "A spore bred to repair damaged land without taking it over. It stops growing at borders no instrument can detect.",
    "artifactForm": "Biotech Module / Fabrication Tool",
    "blueprintRole": "controlled replication",
    "blueprintFamilies": "Planetary Cradle Engine; Spiral Ecology Mesh precursor",
    "civLane": "adaptive biosphere civilization",
    "engineeringScale": "Planetary"
  },
  "t1e02": {
    "id": "t1e02",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 0,
      "abyss": 1,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Voidroot Tap",
    "flavor": "This root draws food from places light cannot reach. Nothing planted above it casts quite the right shadow.",
    "artifactForm": "Biotech Module / Interface",
    "blueprintRole": "nutrient extraction from hidden reservoirs",
    "blueprintFamilies": "Planetary Cradle Engine; Dark-Sector Observatory precursor",
    "civLane": "subterranean adaptive life",
    "engineeringScale": "Planetary"
  },
  "t1e03": {
    "id": "t1e03",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 1,
      "verdance": 0,
      "abyss": 1,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Char Tendril",
    "flavor": "A black tendril searches burned ground for surviving life. It sometimes returns carrying seeds no one planted.",
    "artifactForm": "Biotech Module / Sensor",
    "blueprintRole": "post-fire ecological probing",
    "blueprintFamilies": "Planetary Cradle Engine; Stellar Nursery Rite precursor",
    "civLane": "fire-adapted ecology",
    "engineeringScale": "Planetary"
  },
  "t1e04": {
    "id": "t1e04",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 0,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Climate Seed Die",
    "flavor": "The die prints the first organisms needed to heal a damaged climate. One face has never been used.",
    "artifactForm": "Fabrication Tool / Biotech Module",
    "blueprintRole": "climate repair patterning",
    "blueprintFamilies": "Planetary Cradle Engine; Ecumenopolis Lattice",
    "civLane": "restorative biosphere civilization",
    "engineeringScale": "Planetary"
  },
  "t1e05": {
    "id": "t1e05",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Facetcell Shard",
    "flavor": "Living crystal cells change their purpose as light passes through them. Under moonlight, they arrange themselves into unfamiliar machines.",
    "artifactForm": "Material / Biotech Module",
    "blueprintRole": "cellular optical computation",
    "blueprintFamilies": "Planetary Cradle Engine; Matrioshka Mind precursor",
    "civLane": "crystalline cell ecology",
    "engineeringScale": "Planetary"
  },
  "t1e06": {
    "id": "t1e06",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 1,
      "verdance": 0,
      "abyss": 1,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Decay Lattice",
    "flavor": "The lattice decides how quickly dead matter becomes food again. Certain bones take much longer than they should.",
    "artifactForm": "Biotech Module / Protocol",
    "blueprintRole": "managed decomposition",
    "blueprintFamilies": "Planetary Cradle Engine; Spiral Ecology Mesh precursor",
    "civLane": "recycler biosphere civilization",
    "engineeringScale": "Planetary"
  },
  "t1e07": {
    "id": "t1e07",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 2,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Lichen Vein",
    "flavor": "Engineered lichen grows through stone and closes its cracks. Old walls repaired this way sometimes develop new doorways.",
    "artifactForm": "Biotech Module / Interface",
    "blueprintRole": "stone-life integration",
    "blueprintFamilies": "Ecumenopolis Lattice; Mantle-to-Orbit Foundry",
    "civLane": "urban symbiosis civilization",
    "engineeringScale": "Planetary"
  },
  "t1e08": {
    "id": "t1e08",
    "tier": 1,
    "bonusAffinity": "verdance",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 4,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Necrobloom Bed",
    "flavor": "Dead soil enters the bed; pale life emerges. The blooms occasionally carry memories of the vanished ecosystem.",
    "artifactForm": "Biotech Module / Archive",
    "blueprintRole": "dead-biome reactivation",
    "blueprintFamilies": "Planetary Cradle Engine; Spiral Ecology Mesh precursor",
    "civLane": "thanatological ecology",
    "engineeringScale": "Planetary"
  },
  "t1o01": {
    "id": "t1o01",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 1,
      "verdance": 1,
      "abyss": 0,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Entropy Veil",
    "flavor": "The veil hides the heat of failing machines until repairs arrive. Used too long, it also hides the failure from its owners.",
    "artifactForm": "Defense / Shielding",
    "blueprintRole": "decay masking",
    "blueprintFamilies": "Worldshield Covenant; Heliopause Bastion precursor",
    "civLane": "hidden-survival civilization",
    "engineeringScale": "Planetary"
  },
  "t1o02": {
    "id": "t1o02",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 1,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Horizon Lantern",
    "flavor": "It glows beside boundaries that should not be crossed. The lantern never shows what waits beyond them.",
    "artifactForm": "Sensor / Observatory",
    "blueprintRole": "dangerous boundary detection",
    "blueprintFamilies": "Dark-Sector Observatory precursor; Worldshield Covenant",
    "civLane": "horizon observer culture",
    "engineeringScale": "Planetary"
  },
  "t1o03": {
    "id": "t1o03",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 1,
      "abyss": 0,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Ashen Hollow",
    "flavor": "It preserves the empty shape left by something destroyed. Careful observers can sometimes see the missing object move.",
    "artifactForm": "Containment / Archive",
    "blueprintRole": "absence preserving imprint",
    "blueprintFamilies": "Worldshield Covenant; Spiral-Arm Archive precursor",
    "civLane": "ash-memory civilization",
    "engineeringScale": "Planetary"
  },
  "t1o04": {
    "id": "t1o04",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 2,
      "abyss": 1,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Undergrowth Silencer",
    "flavor": "Living fibers smother sound and signals above hidden settlements. Beneath them, whispers travel farther than radio.",
    "artifactForm": "Defense / Concealment",
    "blueprintRole": "biological noise suppression",
    "blueprintFamilies": "Worldshield Covenant; Spiral Ecology Mesh precursor",
    "civLane": "hidden root civilization",
    "engineeringScale": "Planetary"
  },
  "t1o05": {
    "id": "t1o05",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 2,
      "continuum": 1,
      "verdance": 0,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Blackglass Forge Die",
    "flavor": "A blackglass mold that shapes metal perfectly in airless space. Finished parts emerge cold, even while the forge is burning.",
    "artifactForm": "Fabrication Tool / Material",
    "blueprintRole": "vacuum-stable precision forming",
    "blueprintFamilies": "Mantle-to-Orbit Foundry; Galactic Relic Forge precursor",
    "civLane": "vacuum manufacturing civilization",
    "engineeringScale": "Planetary"
  },
  "t1o06": {
    "id": "t1o06",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 2,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Decay Network",
    "flavor": "This buried web feeds decay back to whatever still lives. Nothing connected to it is ever entirely discarded.",
    "artifactForm": "Protocol / Biotech Module",
    "blueprintRole": "distributed decomposition routing",
    "blueprintFamilies": "Planetary Cradle Engine; Spiral Ecology Mesh precursor",
    "civLane": "subsurface recycler civilization",
    "engineeringScale": "Planetary"
  },
  "t1o07": {
    "id": "t1o07",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 0,
      "abyss": 1,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Absence Shard",
    "flavor": "The shard maps invisible gaps that support impossible structures. It casts no shadow of its own.",
    "artifactForm": "Material / Sensor",
    "blueprintRole": "negative-space reference material",
    "blueprintFamilies": "Dark-Sector Observatory precursor; Worldshield Covenant",
    "civLane": "absence mathematician culture",
    "engineeringScale": "Planetary"
  },
  "t1o08": {
    "id": "t1o08",
    "tier": 1,
    "bonusAffinity": "abyss",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 4,
      "verdance": 0,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Temporal Erasure Seal",
    "flavor": "The seal hides a dangerous hour without erasing it. Every copy bears a date that has not arrived.",
    "artifactForm": "Protocol / Archive",
    "blueprintRole": "limited record redaction",
    "blueprintFamilies": "Causality Audit Court precursor; Worldshield Covenant",
    "civLane": "protective secrecy civilization",
    "engineeringScale": "Planetary"
  },
  "t1p01": {
    "id": "t1p01",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 1,
      "verdance": 0,
      "abyss": 1,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Correction Seed",
    "flavor": "Planted inside a damaged system, it guides the whole toward repair. What returns is healthier, but never quite the same.",
    "artifactForm": "Protocol / Biotech Module",
    "blueprintRole": "error correction in growth or law",
    "blueprintFamilies": "Planetary Cradle Engine; Ecumenopolis Lattice",
    "civLane": "restorative civic biology",
    "engineeringScale": "Planetary"
  },
  "t1p02": {
    "id": "t1p02",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 1,
      "verdance": 0,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Still-Point Shard",
    "flavor": "The shard holds one place perfectly still while everything around it changes. Dust crossing its edge falls in straight lines.",
    "artifactForm": "Control Instrument / Stabilization",
    "blueprintRole": "local equilibrium anchor",
    "blueprintFamilies": "Worldshield Covenant; Causality Audit Court precursor",
    "civLane": "equilibrium civic culture",
    "engineeringScale": "Planetary"
  },
  "t1p03": {
    "id": "t1p03",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 1,
      "abyss": 1,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Prismatic Hollow",
    "flavor": "A hollow prism that separates honest signals from persuasive noise. Lies leave through a face that appears solid.",
    "artifactForm": "Interface / Sensor",
    "blueprintRole": "truth-sorting aperture",
    "blueprintFamilies": "Worldshield Covenant; Dark-Sector Observatory precursor",
    "civLane": "revelatory optics civilization",
    "engineeringScale": "Planetary"
  },
  "t1p04": {
    "id": "t1p04",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Magnetic Bottle",
    "flavor": "Magnetic fields hold star-hot plasma without walls. The bottle hums louder when its contents notice the opening.",
    "artifactForm": "Containment / Power Component",
    "blueprintRole": "plasma or field containment",
    "blueprintFamilies": "Starlift Foundry precursor; Mantle-to-Orbit Foundry",
    "civLane": "field-containment culture",
    "engineeringScale": "Planetary"
  },
  "t1p05": {
    "id": "t1p05",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Recursive Lens",
    "flavor": "Before examining the world, this lens examines its own bias. Occasionally it refuses to show the observer.",
    "artifactForm": "Sensor / Protocol",
    "blueprintRole": "self-auditing perception",
    "blueprintFamilies": "Ascension Registry; Causality Audit Court precursor",
    "civLane": "self-correcting optics culture",
    "engineeringScale": "Planetary"
  },
  "t1p06": {
    "id": "t1p06",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 1,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Living Lattice Node",
    "flavor": "A living junction that lets buildings coordinate their own repair. Unused nodes sometimes begin healing nearby ruins.",
    "artifactForm": "Biotech Module / Civic Signal",
    "blueprintRole": "living civic coordination node",
    "blueprintFamilies": "Ecumenopolis Lattice; Galactic Concordance Engine precursor",
    "civLane": "dense civic ecology",
    "engineeringScale": "Planetary"
  },
  "t1p07": {
    "id": "t1p07",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 0,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 1,
      "abyss": 2,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Void Prism",
    "flavor": "The prism makes forbidden darkness visible, not safe. Something on the other side appears to be looking back.",
    "artifactForm": "Sensor / Interface",
    "blueprintRole": "illumination of hidden void states",
    "blueprintFamilies": "Dark-Sector Observatory precursor; Worldshield Covenant",
    "civLane": "hidden sun civilization",
    "engineeringScale": "Planetary"
  },
  "t1p08": {
    "id": "t1p08",
    "tier": 1,
    "bonusAffinity": "radiance",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 4,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Petrified Bloom",
    "flavor": "A stone flower proving that life once survived here. Its petals open slightly whenever rain approaches.",
    "artifactForm": "Archive / Material",
    "blueprintRole": "preserved life-pattern reference",
    "blueprintFamilies": "Planetary Cradle Engine; Spiral-Arm Archive precursor",
    "civLane": "fossil civic ecology",
    "engineeringScale": "Planetary"
  },
  "t2r01": {
    "id": "t2r01",
    "tier": 2,
    "bonusAffinity": "flare",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 0,
      "abyss": 3,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Stellar Crucible",
    "flavor": "This chamber turns matter drawn from a star into materials no planet can make. Its walls remember every sun they have touched.",
    "artifactForm": "Fabrication Tool / Containment",
    "blueprintRole": "star-powered materials processing",
    "blueprintFamilies": "Starlift Foundry; Galactic Relic Forge precursor",
    "civLane": "stellar industrial civilization",
    "engineeringScale": "Star-system"
  },
  "t2r02": {
    "id": "t2r02",
    "tier": 2,
    "bonusAffinity": "flare",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 1,
      "verdance": 4,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Biomass Ignition Index",
    "flavor": "The index says how much living fuel can be burned without starving the future. Several pages remain permanently sealed.",
    "artifactForm": "Protocol / Biotech Module",
    "blueprintRole": "controlled bioenergy sequencing",
    "blueprintFamilies": "Heliosphere Weather Loom; Arkseed Migration Fleet",
    "civLane": "star-fed biosphere culture",
    "engineeringScale": "Star-system"
  },
  "t2r03": {
    "id": "t2r03",
    "tier": 2,
    "bonusAffinity": "flare",
    "eminence": 2,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Starlift Nozzle",
    "flavor": "This immense nozzle turns stellar fire into a controlled stream of raw material. Its narrowest point is colder than space.",
    "artifactForm": "Control Instrument / Containment",
    "blueprintRole": "stellar matter extraction",
    "blueprintFamilies": "Starlift Foundry",
    "civLane": "pressure-harvesting industrial civilization",
    "engineeringScale": "Star-system"
  },
  "t2r04": {
    "id": "t2r04",
    "tier": 2,
    "bonusAffinity": "flare",
    "eminence": 1,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 2,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Photosynthetic Furnace Wick",
    "flavor": "A living wick carries stored sunlight through the dark between worlds. It continues glowing after the host habitat dies.",
    "artifactForm": "Biotech Module / Power Component",
    "blueprintRole": "habitat-scale light-to-heat conversion",
    "blueprintFamilies": "Heliosphere Weather Loom; Arkseed Migration Fleet",
    "civLane": "stellar greenhouse civilization",
    "engineeringScale": "Star-system"
  },
  "t2r05": {
    "id": "t2r05",
    "tier": 2,
    "bonusAffinity": "flare",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 0,
      "abyss": 2,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Causality Furnace Valve",
    "flavor": "The valve opens only after calculating the harm its power may cause. It has refused orders from every known government.",
    "artifactForm": "Control Instrument / Protocol",
    "blueprintRole": "controlled consequence release",
    "blueprintFamilies": "Causality Audit Court precursor; Starlift Foundry",
    "civLane": "causal-risk engineer civilization",
    "engineeringScale": "Star-system"
  },
  "t2r06": {
    "id": "t2r06",
    "tier": 2,
    "bonusAffinity": "flare",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 5,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Entropy Sink Crucible",
    "flavor": "This crucible turns stellar waste heat into more useful energy. Its final outlet has no recorded destination.",
    "artifactForm": "Power Component / Thermal Control",
    "blueprintRole": "waste heat capture",
    "blueprintFamilies": "Dyson Swarm; Matrioshka Mind",
    "civLane": "thermal accountant civilization",
    "engineeringScale": "Star-system"
  },
  "t2s01": {
    "id": "t2s01",
    "tier": 2,
    "bonusAffinity": "continuum",
    "eminence": 1,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 3,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Interstice Gate Seed",
    "flavor": "A small seed placed where a gateway might one day open. Some begin growing before any route is planned.",
    "artifactForm": "Interface / Transit Component",
    "blueprintRole": "gate-site initialization",
    "blueprintFamilies": "Wormgate Spine precursor; Arkseed Migration Fleet",
    "civLane": "route-planner civilization",
    "engineeringScale": "Star-system"
  },
  "t2s02": {
    "id": "t2s02",
    "tier": 2,
    "bonusAffinity": "continuum",
    "eminence": 2,
    "cost": {
      "flare": 4,
      "continuum": 0,
      "verdance": 0,
      "abyss": 2,
      "radiance": 1,
      "singularity": 0
    },
    "name": "Storm-Memory Filament",
    "flavor": "This filament remembers every solar storm it survives and warns the next world. Its oldest memory predates the star.",
    "artifactForm": "Archive / Sensor",
    "blueprintRole": "stellar weather memory",
    "blueprintFamilies": "Heliosphere Weather Loom; Matrioshka Mind",
    "civLane": "heliosphere archivist culture",
    "engineeringScale": "Star-system"
  },
  "t2s03": {
    "id": "t2s03",
    "tier": 2,
    "bonusAffinity": "continuum",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 0,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Simulation Loom",
    "flavor": "The loom weaves possible futures, then cuts away the deadliest. A few severed threads keep moving.",
    "artifactForm": "Fabrication Tool / Computation Substrate",
    "blueprintRole": "predictive model weaving",
    "blueprintFamilies": "Matrioshka Mind; Causality Audit Court precursor",
    "civLane": "simulation guild civilization",
    "engineeringScale": "Star-system"
  },
  "t2s04": {
    "id": "t2s04",
    "tier": 2,
    "bonusAffinity": "continuum",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 2,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Continuity Vessel",
    "flavor": "The vessel preserves a people's shared identity across centuries of separation. On reunion, it sometimes remembers an extra branch.",
    "artifactForm": "Archive / Containment",
    "blueprintRole": "identity continuity preservation",
    "blueprintFamilies": "Arkseed Migration Fleet; Spiral-Arm Archive precursor",
    "civLane": "migration memory civilization",
    "engineeringScale": "Star-system"
  },
  "t2s05": {
    "id": "t2s05",
    "tier": 2,
    "bonusAffinity": "continuum",
    "eminence": 2,
    "cost": {
      "flare": 5,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Mnemosyne Star-Index",
    "flavor": "It stores many worlds' memories of the same event without choosing one as truth. Contradictions gather near its center.",
    "artifactForm": "Archive / Civic Signal Object",
    "blueprintRole": "multi-world memory indexing",
    "blueprintFamilies": "Matrioshka Mind; Spiral-Arm Archive precursor",
    "civLane": "distributed archive civilization",
    "engineeringScale": "Star-system"
  },
  "t2s06": {
    "id": "t2s06",
    "tier": 2,
    "bonusAffinity": "continuum",
    "eminence": 2,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 0,
      "abyss": 3,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Convergence Lens",
    "flavor": "The lens reveals when different things are being forced into one answer. It cracks under perfect agreement.",
    "artifactForm": "Sensor / Interface",
    "blueprintRole": "wildcard pressure inspection",
    "blueprintFamilies": "Singularity Containment Mandala precursor; Causality Audit Court precursor",
    "civLane": "convergence-risk civilization",
    "engineeringScale": "Star-system"
  },
  "t2e01": {
    "id": "t2e01",
    "tier": 2,
    "bonusAffinity": "verdance",
    "eminence": 1,
    "cost": {
      "flare": 3,
      "continuum": 2,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Solar Immune Organ",
    "flavor": "Grafted into a habitat, this organ teaches life which starlight to accept. It sometimes rejects the home star.",
    "artifactForm": "Biotech Module / Defense",
    "blueprintRole": "radiation adaptation",
    "blueprintFamilies": "Heliosphere Weather Loom; Arkseed Migration Fleet",
    "civLane": "multi-world biosphere civilization",
    "engineeringScale": "Star-system"
  },
  "t2e02": {
    "id": "t2e02",
    "tier": 2,
    "bonusAffinity": "verdance",
    "eminence": 2,
    "cost": {
      "flare": 2,
      "continuum": 4,
      "verdance": 0,
      "abyss": 1,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Dormancy Clock Graft",
    "flavor": "The graft lets whole habitats sleep for centuries and wake on time. Some awaken with one season missing.",
    "artifactForm": "Biotech Module / Archive",
    "blueprintRole": "long-cycle dormancy timing",
    "blueprintFamilies": "Arkseed Migration Fleet; Stellar Nursery Rite",
    "civLane": "deep-time biological culture",
    "engineeringScale": "Star-system"
  },
  "t2e03": {
    "id": "t2e03",
    "tier": 2,
    "bonusAffinity": "verdance",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 3,
      "abyss": 3,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Abyssal Culture Flask",
    "flavor": "A sealed flask where life learns to thrive without light. Shapes gather against the glass when no one is watching.",
    "artifactForm": "Biotech Module / Containment",
    "blueprintRole": "dark-adapted culture growth",
    "blueprintFamilies": "Heliopause Bastion; Spiral Ecology Mesh precursor",
    "civLane": "dark-adapted biosphere culture",
    "engineeringScale": "Star-system"
  },
  "t2e04": {
    "id": "t2e04",
    "tier": 2,
    "bonusAffinity": "verdance",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 0,
      "abyss": 2,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Mycelial Relay Spindle",
    "flavor": "This living spindle translates signals among ships, soil, machines, and flesh. Recently, it began answering messages no one sent.",
    "artifactForm": "Interface / Biotech Module",
    "blueprintRole": "interplanetary biological signaling",
    "blueprintFamilies": "Arkseed Migration Fleet; Heliosphere Weather Loom",
    "civLane": "symbiotic signal civilization",
    "engineeringScale": "Star-system"
  },
  "t2e05": {
    "id": "t2e05",
    "tier": 2,
    "bonusAffinity": "verdance",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 5,
      "verdance": 0,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Epoch Graft Ledger",
    "flavor": "A living ledger grows a new band whenever an age ends. One ring records an era absent from every history.",
    "artifactForm": "Archive / Biotech Module",
    "blueprintRole": "biological era-tracking",
    "blueprintFamilies": "Arkseed Migration Fleet; Spiral-Arm Archive precursor",
    "civLane": "living chronology civilization",
    "engineeringScale": "Star-system"
  },
  "t2e06": {
    "id": "t2e06",
    "tier": 2,
    "bonusAffinity": "verdance",
    "eminence": 2,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 0,
      "abyss": 2,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Crystal Biome Seedplate",
    "flavor": "The seedplate grows habitats that are both crystal and alive. Their first rooms always face the same unknown star.",
    "artifactForm": "Material / Biotech Module",
    "blueprintRole": "crystal-organic habitat seeding",
    "blueprintFamilies": "Heliosphere Weather Loom; Stellar Nursery Rite",
    "civLane": "crystalline ecology civilization",
    "engineeringScale": "Star-system"
  },
  "t2o01": {
    "id": "t2o01",
    "tier": 2,
    "bonusAffinity": "abyss",
    "eminence": 1,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 2,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Horizon Extractor",
    "flavor": "The extractor samples the edge of dangerous physics without crossing it. Something at the boundary occasionally samples back.",
    "artifactForm": "Sensor / Containment",
    "blueprintRole": "boundary-energy sampling",
    "blueprintFamilies": "Dark-Sector Observatory; Starlift Foundry",
    "civLane": "horizon engineer civilization",
    "engineeringScale": "Star-system"
  },
  "t2o02": {
    "id": "t2o02",
    "tier": 2,
    "bonusAffinity": "abyss",
    "eminence": 2,
    "cost": {
      "flare": 1,
      "continuum": 0,
      "verdance": 2,
      "abyss": 0,
      "radiance": 4,
      "singularity": 0
    },
    "name": "Radiant Erasure Casket",
    "flavor": "The casket seals knowledge too dangerous to release. Light still escapes around the lid, spelling no known language.",
    "artifactForm": "Containment / Protocol",
    "blueprintRole": "authorized signal deletion",
    "blueprintFamilies": "Heliopause Bastion; Worldshield Covenant",
    "civLane": "lawful redaction civilization",
    "engineeringScale": "Star-system"
  },
  "t2o03": {
    "id": "t2o03",
    "tier": 2,
    "bonusAffinity": "abyss",
    "eminence": 2,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 0,
      "abyss": 3,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Entropic Furnace Baffle",
    "flavor": "This baffle hides and reuses the heat that would reveal a starbound people. Even nearby suns seem dimmer around it.",
    "artifactForm": "Thermal Control / Defense",
    "blueprintRole": "entropy redirection",
    "blueprintFamilies": "Starlift Foundry; Matrioshka Mind",
    "civLane": "waste-heat shadow culture",
    "engineeringScale": "Star-system"
  },
  "t2o04": {
    "id": "t2o04",
    "tier": 2,
    "bonusAffinity": "abyss",
    "eminence": 1,
    "cost": {
      "flare": 2,
      "continuum": 0,
      "verdance": 3,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Extinction Forge Die",
    "flavor": "Forged from the ruins of failed worlds, this die makes parts for whatever comes next. Every copy bears the same fracture.",
    "artifactForm": "Fabrication Tool / Archive",
    "blueprintRole": "post-collapse reconstruction tooling",
    "blueprintFamilies": "Galactic Relic Forge precursor; Spiral-Arm Archive precursor",
    "civLane": "extinction-survivor culture",
    "engineeringScale": "Star-system"
  },
  "t2o05": {
    "id": "t2o05",
    "tier": 2,
    "bonusAffinity": "abyss",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 5,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Eventide Ecology Seal",
    "flavor": "The seal lets an ecosystem sleep instead of starving as its light fades. Dormant roots continue counting the years.",
    "artifactForm": "Protocol / Biotech Module",
    "blueprintRole": "managed ecological shutdown",
    "blueprintFamilies": "Heliosphere Weather Loom; Spiral Ecology Mesh precursor",
    "civLane": "twilight ecology civilization",
    "engineeringScale": "Star-system"
  },
  "t2o06": {
    "id": "t2o06",
    "tier": 2,
    "bonusAffinity": "abyss",
    "eminence": 2,
    "cost": {
      "flare": 2,
      "continuum": 3,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Dimensional Shear Gauge",
    "flavor": "The gauge warns when stressed space is about to tear. Its needle trembles near certain people.",
    "artifactForm": "Sensor / Interface",
    "blueprintRole": "boundary stress measurement",
    "blueprintFamilies": "Heliopause Bastion; Wormgate Spine precursor",
    "civLane": "spatial stress engineer civilization",
    "engineeringScale": "Star-system"
  },
  "t2p01": {
    "id": "t2p01",
    "tier": 2,
    "bonusAffinity": "radiance",
    "eminence": 1,
    "cost": {
      "flare": 2,
      "continuum": 3,
      "verdance": 0,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Containment Lattice",
    "flavor": "Every dangerous chamber in this lattice can be inspected from outside. One sealed cell appears empty from every angle.",
    "artifactForm": "Containment / Civic Signal",
    "blueprintRole": "public-safe hazardous containment",
    "blueprintFamilies": "Starlift Foundry; Singularity Containment Mandala precursor",
    "civLane": "transparent containment civilization",
    "engineeringScale": "Star-system"
  },
  "t2p02": {
    "id": "t2p02",
    "tier": 2,
    "bonusAffinity": "radiance",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 1,
      "abyss": 4,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Null-Convergence Prism",
    "flavor": "The prism glows when many meanings are crushed into one convenient answer. Its brightest flare has never been explained.",
    "artifactForm": "Sensor / Interface",
    "blueprintRole": "category collapse warning",
    "blueprintFamilies": "Singularity Containment Mandala precursor; Matrioshka Mind",
    "civLane": "convergence-auditing civilization",
    "engineeringScale": "Star-system"
  },
  "t2p03": {
    "id": "t2p03",
    "tier": 2,
    "bonusAffinity": "radiance",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 3,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Living Treaty Organ",
    "flavor": "This living organ holds an agreement between worlds as flesh, not paper. Breaking the treaty makes it bleed.",
    "artifactForm": "Biotech Module / Civic Protocol",
    "blueprintRole": "multi-world biological governance",
    "blueprintFamilies": "Heliosphere Weather Loom; Galactic Concordance Engine precursor",
    "civLane": "plural civic ecology",
    "engineeringScale": "Star-system"
  },
  "t2p04": {
    "id": "t2p04",
    "tier": 2,
    "bonusAffinity": "radiance",
    "eminence": 1,
    "cost": {
      "flare": 3,
      "continuum": 2,
      "verdance": 0,
      "abyss": 0,
      "radiance": 2,
      "singularity": 0
    },
    "name": "Heliostat Filament",
    "flavor": "A single filament teaches vast mirrors how to steer a star's light. At night, it points beyond the system.",
    "artifactForm": "Power Component / Signal Object",
    "blueprintRole": "stellar light alignment",
    "blueprintFamilies": "Dyson Swarm; Heliosphere Weather Loom",
    "civLane": "solar coordination civilization",
    "engineeringScale": "Star-system"
  },
  "t2p05": {
    "id": "t2p05",
    "tier": 2,
    "bonusAffinity": "radiance",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 0,
      "abyss": 0,
      "radiance": 5,
      "singularity": 0
    },
    "name": "Error-Correcting Core",
    "flavor": "The core finds and repairs mistakes across vast distances. It keeps a private record of errors that should have been impossible.",
    "artifactForm": "Computation Substrate / Protocol",
    "blueprintRole": "high-energy error correction",
    "blueprintFamilies": "Matrioshka Mind; Causality Audit Court precursor",
    "civLane": "precision computation civilization",
    "engineeringScale": "Star-system"
  },
  "t2p06": {
    "id": "t2p06",
    "tier": 2,
    "bonusAffinity": "radiance",
    "eminence": 2,
    "cost": {
      "flare": 0,
      "continuum": 2,
      "verdance": 3,
      "abyss": 2,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Radiation Treaty Prism",
    "flavor": "The prism divides stellar radiation fairly among many habitats. One face accepts a burden assigned to no world.",
    "artifactForm": "Civic Signal / Sensor",
    "blueprintRole": "shared radiation governance",
    "blueprintFamilies": "Heliosphere Weather Loom; Arkseed Migration Fleet",
    "civLane": "multi-world biosphere treaty culture",
    "engineeringScale": "Star-system"
  },
  "t3r01": {
    "id": "t3r01",
    "tier": 3,
    "bonusAffinity": "flare",
    "eminence": 3,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 0,
      "abyss": 5,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Ignition Reliquary",
    "flavor": "Across the galaxy, this network preserves how every tended star first ignited. Dead suns sometimes answer before the relighting begins.",
    "artifactForm": "Galactic Energy Network / Archive",
    "blueprintRole": "stellar ignition continuity",
    "blueprintFamilies": "Stellar Nursery Rite; Galactic Relic Forge",
    "civLane": "stellar lineage civilization",
    "engineeringScale": "Galactic"
  },
  "t3r02": {
    "id": "t3r02",
    "tier": 3,
    "bonusAffinity": "flare",
    "eminence": 4,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 3,
      "abyss": 6,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Extinction Furnace",
    "flavor": "The Furnace dismantles dying stars and ruined megastructures, returning their matter to the galaxy. Every use is witnessed; not every witness returns.",
    "artifactForm": "Galactic Disassembly Megastructure / Power Infrastructure",
    "blueprintRole": "terminal-system disassembly",
    "blueprintFamilies": "Causality Audit Court; Black-Map Pilgrimage Engine",
    "civLane": "catastrophe-governance civilization",
    "engineeringScale": "Galactic"
  },
  "t3r03": {
    "id": "t3r03",
    "tier": 3,
    "bonusAffinity": "flare",
    "eminence": 3,
    "cost": {
      "flare": 0,
      "continuum": 5,
      "verdance": 0,
      "abyss": 3,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Chronoflare Array",
    "flavor": "The Array times stellar flares across the galaxy so distant systems receive power together. Its countdown begins at different numbers everywhere.",
    "artifactForm": "Galactic Energy Array / Chronology Infrastructure",
    "blueprintRole": "synchronized galactic power",
    "blueprintFamilies": "Causality Audit Court; Matrioshka Chorus precursor",
    "civLane": "relativistic energy civilization",
    "engineeringScale": "Galactic"
  },
  "t3r04": {
    "id": "t3r04",
    "tier": 3,
    "bonusAffinity": "flare",
    "eminence": 5,
    "cost": {
      "flare": 0,
      "continuum": 0,
      "verdance": 7,
      "abyss": 3,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Star-River Crucible",
    "flavor": "A river of stellar matter flows through galactic foundries and emerges as habitats, engines, and young worlds. Some arrive already inhabited.",
    "artifactForm": "Galactic Fabrication Infrastructure / Biotech Interface",
    "blueprintRole": "living megastructure fabrication",
    "blueprintFamilies": "Star-River Migration Lattice; Galactic Relic Forge",
    "civLane": "living industrial expansion civilization",
    "engineeringScale": "Galactic"
  },
  "t3s01": {
    "id": "t3s01",
    "tier": 3,
    "bonusAffinity": "continuum",
    "eminence": 3,
    "cost": {
      "flare": 5,
      "continuum": 3,
      "verdance": 0,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Wormgate Spine",
    "flavor": "A chain of wormgates forms the galaxy's great road. When one gate fails, the Spine quietly remembers another route.",
    "artifactForm": "Galactic Transit Megastructure / Control Network",
    "blueprintRole": "galactic transit continuity",
    "blueprintFamilies": "Black-Map Pilgrimage Engine; Extragalactic Gatework",
    "civLane": "interstellar transit civilization",
    "engineeringScale": "Galactic"
  },
  "t3s02": {
    "id": "t3s02",
    "tier": 3,
    "bonusAffinity": "continuum",
    "eminence": 4,
    "cost": {
      "flare": 6,
      "continuum": 3,
      "verdance": 0,
      "abyss": 3,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Recursive Commonwealth",
    "flavor": "Separated societies let their laws diverge, then use the Commonwealth to reconcile. Sometimes it preserves a decision no society recalls making.",
    "artifactForm": "Distributed Civic Continuity Network / Protocol Infrastructure",
    "blueprintRole": "distributed civic reconciliation",
    "blueprintFamilies": "Causality Audit Court; Galactic Concordance",
    "civLane": "plural continuity civilization",
    "engineeringScale": "Galactic"
  },
  "t3s03": {
    "id": "t3s03",
    "tier": 3,
    "bonusAffinity": "continuum",
    "eminence": 3,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 5,
      "abyss": 3,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Extinction Archive",
    "flavor": "The Archive keeps the voices, jokes, failures, and unfinished warnings of extinct peoples. A few records are still receiving replies.",
    "artifactForm": "Galactic Archive Network / Civic Signal",
    "blueprintRole": "extinct-civilization memory",
    "blueprintFamilies": "Spiral-Arm Archive; Galactic Concordance",
    "civLane": "galactic archivist civilization",
    "engineeringScale": "Galactic"
  },
  "t3s04": {
    "id": "t3s04",
    "tier": 3,
    "bonusAffinity": "continuum",
    "eminence": 5,
    "cost": {
      "flare": 3,
      "continuum": 7,
      "verdance": 0,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Chronology Accord",
    "flavor": "The Accord lets worlds with different clocks share one history. It contains dates that every participant insists came first.",
    "artifactForm": "Galactic Chronology Infrastructure / Civic Protocol",
    "blueprintRole": "galactic chronology governance",
    "blueprintFamilies": "Causality Audit Court; Spiral-Arm Archive",
    "civLane": "chronology-governing civilization",
    "engineeringScale": "Galactic"
  },
  "t3e01": {
    "id": "t3e01",
    "tier": 3,
    "bonusAffinity": "verdance",
    "eminence": 3,
    "cost": {
      "flare": 0,
      "continuum": 5,
      "verdance": 3,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Worldroot Lattice",
    "flavor": "Living roots carry nutrients, defenses, and dormant life between worlds without making them alike. Some routes grow toward uncharted planets.",
    "artifactForm": "Galactic Biosphere Network / Transit Ecology",
    "blueprintRole": "biosphere propagation",
    "blueprintFamilies": "Spiral Ecology Mesh; Star-River Migration Lattice",
    "civLane": "interstellar symbiotic civilization",
    "engineeringScale": "Galactic"
  },
  "t3e02": {
    "id": "t3e02",
    "tier": 3,
    "bonusAffinity": "verdance",
    "eminence": 4,
    "cost": {
      "flare": 3,
      "continuum": 6,
      "verdance": 0,
      "abyss": 3,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Stellar Overgrowth",
    "flavor": "Vast living structures surround stars, turning light into habitats and new ecologies. No two grow the same, even from identical seeds.",
    "artifactForm": "Living Stellar Infrastructure / Power Ecology",
    "blueprintRole": "star-integrated ecology",
    "blueprintFamilies": "Spiral Ecology Mesh; Stellar Nursery Rite",
    "civLane": "stellar ecology civilization",
    "engineeringScale": "Galactic"
  },
  "t3e03": {
    "id": "t3e03",
    "tier": 3,
    "bonusAffinity": "verdance",
    "eminence": 3,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 0,
      "abyss": 5,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Interstellar Necrobiome",
    "flavor": "The Necrobiome turns dead worlds and ruined habitats into safe soil for new life. It remembers what consumed them.",
    "artifactForm": "Galactic Recovery Ecology / Archive",
    "blueprintRole": "dead-system reclamation",
    "blueprintFamilies": "Spiral Ecology Mesh; Spiral-Arm Archive",
    "civLane": "ancestral recycler civilization",
    "engineeringScale": "Galactic"
  },
  "t3e04": {
    "id": "t3e04",
    "tier": 3,
    "bonusAffinity": "verdance",
    "eminence": 5,
    "cost": {
      "flare": 3,
      "continuum": 3,
      "verdance": 7,
      "abyss": 0,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Biosphere Concordance",
    "flavor": "The Concordance lets alien ecologies exchange food, air, and microbes without one consuming the others. Contact leaves both sides changed.",
    "artifactForm": "Galactic Ecology Coordination Network / Biotech Protocol",
    "blueprintRole": "ecological coexistence",
    "blueprintFamilies": "Galactic Concordance; Spiral Ecology Mesh",
    "civLane": "plural biosphere civilization",
    "engineeringScale": "Galactic"
  },
  "t3o01": {
    "id": "t3o01",
    "tier": 3,
    "bonusAffinity": "abyss",
    "eminence": 3,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 5,
      "abyss": 3,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Cryptobiotic Constellation",
    "flavor": "Hidden refuge worlds sleep across the galaxy, each able to wake the others after catastrophe. Maps show only lifeless stone.",
    "artifactForm": "Galactic Concealment Network / Biosphere Reserve",
    "blueprintRole": "hidden biosphere preservation",
    "blueprintFamilies": "Spiral Ecology Mesh; Dark-Sector Observatory",
    "civLane": "buried survival civilization",
    "engineeringScale": "Galactic"
  },
  "t3o02": {
    "id": "t3o02",
    "tier": 3,
    "bonusAffinity": "abyss",
    "eminence": 4,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 6,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Collapse Mandala",
    "flavor": "The Mandala surrounds black holes, dying worlds, and spreading collapses with observation and containment. Its innermost ring is always empty.",
    "artifactForm": "Galactic Containment Network / Observatory",
    "blueprintRole": "collapse containment",
    "blueprintFamilies": "Singularity Containment Mandala; Causality Audit Court",
    "civLane": "collapse-auditing civilization",
    "engineeringScale": "Galactic"
  },
  "t3o03": {
    "id": "t3o03",
    "tier": 3,
    "bonusAffinity": "abyss",
    "eminence": 3,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 3,
      "abyss": 0,
      "radiance": 5,
      "singularity": 0
    },
    "name": "Ordered Silence",
    "flavor": "Buried relays and false constellations let threatened worlds speak without being found. Some decoys have begun sending real messages.",
    "artifactForm": "Galactic Concealment Infrastructure / Signal Protocol",
    "blueprintRole": "galactic signal discipline",
    "blueprintFamilies": "Dark-Sector Observatory; Black-Map Pilgrimage Engine",
    "civLane": "silent survival civilization",
    "engineeringScale": "Galactic"
  },
  "t3o04": {
    "id": "t3o04",
    "tier": 3,
    "bonusAffinity": "abyss",
    "eminence": 5,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 3,
      "abyss": 7,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Dark-Sector Aperture",
    "flavor": "This vast boundary lets the galaxy observe a forbidden dark sector without opening passage. Every instrument faces both ways.",
    "artifactForm": "Galactic Observatory Megastructure / Boundary Interface",
    "blueprintRole": "forbidden-sector observation",
    "blueprintFamilies": "Dark-Sector Observatory; Black-Map Pilgrimage Engine",
    "civLane": "hidden observer civilization",
    "engineeringScale": "Galactic"
  },
  "t3p01": {
    "id": "t3p01",
    "tier": 3,
    "bonusAffinity": "radiance",
    "eminence": 3,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 3,
      "abyss": 5,
      "radiance": 0,
      "singularity": 0
    },
    "name": "Galactic Concordance",
    "flavor": "Courts and enforcement stations bind many species without a galactic capital. The Concordance has no throne, though someone keeps building one.",
    "artifactForm": "Galactic Civic Institution / Enforcement Network",
    "blueprintRole": "multi-species legitimacy",
    "blueprintFamilies": "Causality Audit Court; Biosphere Concordance",
    "civLane": "plural civic civilization",
    "engineeringScale": "Galactic"
  },
  "t3p02": {
    "id": "t3p02",
    "tier": 3,
    "bonusAffinity": "radiance",
    "eminence": 4,
    "cost": {
      "flare": 3,
      "continuum": 0,
      "verdance": 3,
      "abyss": 0,
      "radiance": 6,
      "singularity": 0
    },
    "name": "Relic Forge Commons",
    "flavor": "Shared foundries build civilization-changing works in full public view. One production line appears on no approved plan.",
    "artifactForm": "Galactic Fabrication Network / Civic Infrastructure",
    "blueprintRole": "accountable relic manufacture",
    "blueprintFamilies": "Galactic Relic Forge; Matrioshka Chorus precursor",
    "civLane": "public maker civilization",
    "engineeringScale": "Galactic"
  },
  "t3p03": {
    "id": "t3p03",
    "tier": 3,
    "bonusAffinity": "radiance",
    "eminence": 3,
    "cost": {
      "flare": 5,
      "continuum": 0,
      "verdance": 3,
      "abyss": 0,
      "radiance": 3,
      "singularity": 0
    },
    "name": "Matrioshka Chorus",
    "flavor": "Thousands of star-sized minds solve problems together without becoming one mind. Between calculations, the Chorus dreams in disagreement.",
    "artifactForm": "Galactic Computation Network / Civic Protocol",
    "blueprintRole": "plural galactic computation",
    "blueprintFamilies": "Matrioshka Mind; Causality Audit Court",
    "civLane": "accountable computation civilization",
    "engineeringScale": "Galactic"
  },
  "t3p04": {
    "id": "t3p04",
    "tier": 3,
    "bonusAffinity": "radiance",
    "eminence": 5,
    "cost": {
      "flare": 0,
      "continuum": 3,
      "verdance": 0,
      "abyss": 3,
      "radiance": 7,
      "singularity": 0
    },
    "name": "Witness Constellation",
    "flavor": "Independent stations preserve evidence of erased histories and broken rights. No ruler knows where every witness is.",
    "artifactForm": "Galactic Verification Network / Civic Observatory",
    "blueprintRole": "public rights verification",
    "blueprintFamilies": "Spiral-Arm Archive; Causality Audit Court",
    "civLane": "multi-species witness civilization",
    "engineeringScale": "Galactic"
  }
} as const;
