// Kept in sync with the server lore catalog so dev-only card review works
// when the API service is not running.
export const CARD_NAME_FALLBACK: Readonly<Record<string, string>> =
  Object.freeze({
    t1r01: "Ignition Kernel",
    t1r02: "Ashroot Bloom",
    t1r03: "Chrono-Ember Core",
    t1r04: "Causal Spark Coil",
    t1r05: "Voidflare Cask",
    t1r06: "Photosynthetic Wick",
    t1r07: "Entropy Pyre Baffle",
    t1r08: "Oathfire Igniter",
    t1s01: "Echo Splinter",
    t1s02: "Mantlelift Driver Coil",
    t1s03: "Null-Loop Anchor",
    t1s04: "Time-Crystal Scaffold",
    t1s05: "Silent Recursion Rule",
    t1s06: "Living Chronicle",
    t1s07: "String-Scar Loom",
    t1s08: "Root Memory Valve",
    t1e01: "Replication Spore",
    t1e02: "Voidroot Tap",
    t1e03: "Char Tendril",
    t1e04: "Climate Seed Die",
    t1e05: "Facetcell Shard",
    t1e06: "Decay Lattice",
    t1e07: "Lichen Vein",
    t1e08: "Necrobloom Bed",
    t1o01: "Entropy Veil",
    t1o02: "Horizon Lantern",
    t1o03: "Ashen Hollow",
    t1o04: "Undergrowth Silencer",
    t1o05: "Blackglass Forge Die",
    t1o06: "Decay Network",
    t1o07: "Absence Shard",
    t1o08: "Temporal Erasure Seal",
    t1p01: "Correction Seed",
    t1p02: "Still-Point Shard",
    t1p03: "Prismatic Hollow",
    t1p04: "Magnetic Bottle",
    t1p05: "Recursive Lens",
    t1p06: "Living Lattice Node",
    t1p07: "Void Prism",
    t1p08: "Petrified Bloom",
    t2r01: "Stellar Crucible",
    t2r02: "Biomass Ignition Index",
    t2r03: "Starlift Nozzle",
    t2r04: "Photosynthetic Furnace Wick",
    t2r05: "Causality Furnace Valve",
    t2r06: "Entropy Sink Crucible",
    t2s01: "Interstice Gate Seed",
    t2s02: "Storm-Memory Filament",
    t2s03: "Simulation Loom",
    t2s04: "Continuity Vessel",
    t2s05: "Mnemosyne Star-Index",
    t2s06: "Convergence Lens",
    t2e01: "Solar Immune Organ",
    t2e02: "Dormancy Clock Graft",
    t2e03: "Abyssal Culture Flask",
    t2e04: "Mycelial Relay Spindle",
    t2e05: "Epoch Graft Ledger",
    t2e06: "Crystal Biome Seedplate",
    t2o01: "Horizon Extractor",
    t2o02: "Radiant Erasure Casket",
    t2o03: "Entropic Furnace Baffle",
    t2o04: "Extinction Forge Die",
    t2o05: "Eventide Ecology Seal",
    t2o06: "Dimensional Shear Gauge",
    t2p01: "Containment Lattice",
    t2p02: "Null-Convergence Prism",
    t2p03: "Living Treaty Organ",
    t2p04: "Heliostat Filament",
    t2p05: "Error-Correcting Core",
    t2p06: "Radiation Treaty Prism",
    t3r01: "Relicfire Interpreter",
    t3r02: "Terminal-System Reclaimer",
    t3r03: "Chronoflare Phase Regulator",
    t3r04: "Plural Habitat Forge Heart",
    t3s01: "Voidline Route Solver",
    t3s02: "Divergence Reconciler",
    t3s03: "Extinction Signal Decoder",
    t3s04: "Relativistic Chronology Governor",
    t3e01: "Xenobiome Route Graft",
    t3e02: "Stellar Habitat Genome",
    t3e03: "Extinction Immunome",
    t3e04: "Biosphere Translation Membrane",
    t3o01: "Refuge Dormancy Kernel",
    t3o02: "Collapse Forecast Engine",
    t3o03: "Quiet-Signal Symbiont",
    t3o04: "Null-Baseline Interferometer",
    t3p01: "Plurality Accord Verifier",
    t3p02: "Relic Provenance Standard",
    t3p03: "Federated Logic Substrate",
    t3p04: "Species-Rights Witness",
  });
